[labels]
app.name = Air
errors.identity_changed = Jou rekening het verander. Herlaai voor jy stoor.
errors.invalid_request = Ongeldige versoek
errors.missing_field = Verpligte veld ontbreek
errors.not_found = Nie gevind nie
errors.not_logged_in = Meld aan om voort te gaan
errors.body_is_required = Tik asseblief iets voordat jy indien
errors.body_too_long = Jou boodskap is te lank
errors.title_is_required = Gee asseblief jou plasing 'n titel
errors.title_too_long = Jou titel is te lank
errors.remote_failed = Afgeleë versoek het misluk
errors.service_unavailable = Die indieningsdiens is tydelik onbeskikbaar. Probeer asseblief later weer.
errors.forum_not_found = Forum nie gevind nie
errors.forum_not_found_in_directory = Forum nie in gids gevind nie
errors.not_allowed_to_post = Nie toegelaat om te plaas nie
errors.access_denied = Toegang geweier
errors.remote = Die eksterne bediener kon nie die versoek voltooi nie
errors.unable_to_connect_to_server = Kan nie aan bediener koppel nie
errors.invalid_post_id = Ongeldige plasings-ID
errors.invalid_title = Ongeldige titel
errors.invalid_body = Ongeldige inhoud
errors.invalid_id = Ongeldige ID

attachment.errors.denied = Toegang geweier
attachment.errors.not_found = Aanhangsel nie gevind nie
attachment.errors.unavailable = Aanhegsel tydelik nie beskikbaar nie
