[labels]
app.name = Air
errors.identity_changed = መለያዎ ተቀይሯል። ከማስቀመጥዎ በፊት እንደገና ይጫኑ።
errors.invalid_request = ልክ ያልሆነ ጥያቄ
errors.missing_field = አስፈላጊ መስክ ይጎድላል
errors.not_found = አልተገኘም
errors.not_logged_in = ለመቀጠል ይግቡ
errors.body_is_required = እባክዎ ከማስገባትዎ በፊት የሆነ ነገር ይተይቡ
errors.body_too_long = መልእክትዎ በጣም ረጅም ነው
errors.title_is_required = እባክዎ ለልጥፍዎ ርዕስ ይስጡ
errors.title_too_long = ርዕስዎ በጣም ረጅም ነው
errors.remote_failed = የርቀት ጥያቄ አልተሳካም
errors.service_unavailable = የማስገቢያ አገልግሎቱ ለጊዜው አይገኝም። እባክዎ ቆይተው እንደገና ይሞክሩ።
errors.forum_not_found = መድረክ አልተገኘም
errors.forum_not_found_in_directory = መድረክ በማውጫ ውስጥ አልተገኘም
errors.not_allowed_to_post = መለጠፍ አልተፈቀደም
errors.access_denied = መዳረሻ ተከልክሏል
errors.remote = የርቀት አገልጋዩ ጥያቄውን ማጠናቀቅ አልቻለም
errors.unable_to_connect_to_server = ከሰርቨር ጋር መገናኘት አልተቻለም
errors.invalid_post_id = ልክ ያልሆነ የልጥፍ መታወቂያ
errors.invalid_title = ልክ ያልሆነ ርዕስ
errors.invalid_body = ልክ ያልሆነ ይዘት
errors.invalid_id = ልክ ያልሆነ መታወቂያ

attachment.errors.denied = መዳረሻ ተከልክሏል
attachment.errors.not_found = አባሪ አልተገኘም
attachment.errors.unavailable = ዓባሪ ለጊዜው አይገኝም
