[labels]
app.name = Air
errors.identity_changed = መለያዎ ተቀይሯል። ከማስቀመጥዎ በፊት እንደገና ይጫኑ።
errors.invalid_request = ልክ ያልሆነ ጥያቄ
errors.missing_field = አስፈላጊ መስክ ይጎድላል
errors.not_found = አልተገኘም
errors.not_logged_in = ለመቀጠል ይግቡ
