[labels]
app.name = Air
errors.identity_changed = Cuentamax mayjt'ayatawa. Janïr imkasax laphi machaqacham.
errors.invalid_request = Mayiwi jan walikiti
errors.missing_field = Wakisir campox janiw utjkiti
errors.not_found = Janiw jikxatatäkiti
errors.not_logged_in = Sarantañataki mantam
errors.body_is_required = Janïr apayasax juk'amp detallenak yapxatam
errors.body_too_long = Mensajemax sinti jach'awa
errors.title_is_required = Qillqatamar mä título uchaña
errors.title_too_long = Títulomax sinti jach'awa
errors.remote_failed = Jaya mayiwix pantjawayi
errors.service_unavailable = Apayañ servicio jichhax janiw utjkiti. Qhipat wasitat yant'am.
errors.forum_not_found = Foro jan jikxatasiti
errors.forum_not_found_in_directory = Foro directorion jan jikxatasiti
errors.not_allowed_to_post = Qillqañax janiw iyawsatäkiti
errors.access_denied = Mantañ jark'ata
errors.remote = Jaya servidorax janiw mayiwi tukuyañ atkiti
errors.unable_to_connect_to_server = Servidorar janiw chikacht'asiñjamäkiti
errors.invalid_post_id = Qillqata ID jan walikiti
errors.invalid_title = Título jan walikiti
errors.invalid_body = Contenido jan walikiti
errors.invalid_id = ID jan walikiti

attachment.errors.denied = Mantañ jark'ata
attachment.errors.not_found = Adjunto jan jikxatasiti
attachment.errors.unavailable = Adjuntox jichhax jan utjkiti
