[labels]
app.name = Air
errors.identity_changed = Cuentamax mayjt'awa. Jan imañkama wasitat qhanancham.
errors.invalid_request = Mayiwi jan walikiti
errors.missing_field = Wakisir cheqa chhaqhatawa
errors.not_found = Janiw jikxatatäkiti
errors.not_logged_in = Sarantañataki mantam

attachment.errors.denied = Mantañ jark'ata
attachment.errors.not_found = Attachment jan jikxatasiti
attachment.errors.unavailable = Chimpu jan jichhakama utjkiti
