[labels]
app.name = Air
errors.identity_changed = Cuentamax mayjt'awa. Jan imañkama wasitat qhanancham.
errors.invalid_request = Jan wali mayiwi
errors.missing_field = Wakisir cheqa chhaqhatawa
errors.not_found = Jan jikitäki
errors.not_logged_in = Sarantañataki mantam
