[labels]
app.name = Air
errors.identity_changed = Hesabınız dəyişdi. Yadda saxlamadan əvvəl yenidən yükləyin.
errors.invalid_request = Etibarsız sorğu
errors.missing_field = Tələb olunan sahə çatışmır
errors.not_found = Tapılmadı
errors.not_logged_in = Davam etmək üçün daxil olun
errors.body_is_required = Göndərmədən əvvəl lütfən nəsə yazın
errors.body_too_long = Mesajınız çox uzundur
errors.title_is_required = Lütfən paylaşımınıza başlıq verin
errors.title_too_long = Başlığınız çox uzundur
errors.remote_failed = Uzaq sorğu uğursuz oldu
errors.service_unavailable = Göndərmə xidməti müvəqqəti olaraq əlçatan deyil. Zəhmət olmasa, daha sonra yenidən cəhd edin.
errors.forum_not_found = Forum tapılmadı
errors.forum_not_found_in_directory = Forum kataloqda tapılmadı
errors.not_allowed_to_post = Post yazmağa icazə verilmir
errors.access_denied = Giriş rədd edildi
errors.remote = Uzaq server sorğunu tamamlaya bilmədi
errors.unable_to_connect_to_server = Serverə qoşulmaq mümkün deyil
errors.invalid_post_id = Etibarsız post ID
errors.invalid_title = Etibarsız başlıq
errors.invalid_body = Etibarsız məzmun
errors.invalid_id = Etibarsız ID

attachment.errors.denied = Giriş rədd edildi
attachment.errors.not_found = Qoşma tapılmadı
attachment.errors.unavailable = Qoşma müvəqqəti əlçatan deyil
