[labels]
app.name = Air
errors.identity_changed = Ваш уліковы запіс змяніўся. Перазагрузіце перад захаваннем.
errors.invalid_request = Няправільны запыт
errors.missing_field = Адсутнічае абавязковае поле
errors.not_found = Не знойдзена
errors.not_logged_in = Увайдзіце, каб працягнуць
errors.body_is_required = Увядзіце тэкст перад адпраўкай
errors.body_too_long = Ваша паведамленне занадта доўгае
errors.title_is_required = Дайце загаловак вашай публікацыі
errors.title_too_long = Ваш загаловак занадта доўгі
errors.remote_failed = Аддалены запыт не выкананы
errors.service_unavailable = Сэрвіс адпраўкі часова недаступны. Калі ласка, паспрабуйце пазней.
errors.forum_not_found = Форум не знойдзены
errors.forum_not_found_in_directory = Форум не знойдзены ў каталогу
errors.not_allowed_to_post = Не дазволена публікаваць
errors.access_denied = Доступ забаронены
errors.remote = Аддалены сервер не змог выканаць запыт
errors.unable_to_connect_to_server = Не ўдалося падключыцца да сервера
errors.invalid_post_id = Некарэктны ID паста
errors.invalid_title = Некарэктная назва
errors.invalid_body = Некарэктнае цела
errors.invalid_id = Некарэктны ID

attachment.errors.denied = Доступ забаронены
attachment.errors.not_found = Укладанне не знойдзена
attachment.errors.unavailable = Далучэнне часова недаступнае
