[labels]
app.name = Air
errors.identity_changed = Ваш уліковы запіс змяніўся. Перазагрузіце перад захаваннем.
errors.invalid_request = Няправільны запыт
errors.missing_field = Адсутнічае абавязковае поле
errors.not_found = Не знойдзена
errors.not_logged_in = Увайдзіце, каб працягнуць
