[labels]
app.name = Air
errors.identity_changed = राउर खाता बदल गइल। सेव करे से पहिले फेर से लोड करीं।
errors.invalid_request = अमान्य अनुरोध
errors.missing_field = जरूरी फील्ड गायब बा
errors.not_found = ना मिलल
errors.not_logged_in = जारी राखे खातिर साइन इन करीं
errors.body_is_required = कृपया सबमिट करे से पहिले कुछ लिखीं
errors.body_too_long = रउआ के संदेश बहुत लंबा बा
errors.title_is_required = कृपया आपन पोस्ट के एगो शीर्षक दीं
errors.title_too_long = रउआ के शीर्षक बहुत लंबा बा
errors.remote_failed = दूरस्थ अनुरोध विफल भइल
errors.service_unavailable = जमा करे वाली सेवा अस्थायी रूप से उपलब्ध नइखे। कृपया बाद में फिर से कोसिस करीं।
errors.forum_not_found = फोरम ना मिलल
errors.forum_not_found_in_directory = डायरेक्टरी में फोरम ना मिलल
errors.not_allowed_to_post = पोस्ट करे के अनुमति नइखे
errors.access_denied = पहुंच मना
errors.remote = रिमोट सर्वर अनुरोध पूरा ना कर पवलस
errors.unable_to_connect_to_server = सर्वर से जुड़ल असमर्थ
errors.invalid_post_id = अमान्य पोस्ट ID
errors.invalid_title = अमान्य शीर्षक
errors.invalid_body = अमान्य बॉडी
errors.invalid_id = अमान्य ID

attachment.errors.denied = पहुंच मना
attachment.errors.not_found = अटैचमेंट ना मिलल
attachment.errors.unavailable = अटैचमेंट अभी उपलब्ध नइखे
