[labels]
app.name = Air
errors.identity_changed = আপনার অ্যাকাউন্ট পরিবর্তিত হয়েছে। সংরক্ষণের আগে পুনরায় লোড করুন।
errors.invalid_request = অবৈধ অনুরোধ
errors.missing_field = আবশ্যক ক্ষেত্র অনুপস্থিত
errors.not_found = খুঁজে পাওয়া যায়নি
errors.not_logged_in = চালিয়ে যেতে সাইন ইন করুন
errors.body_is_required = অনুগ্রহ করে জমা দেওয়ার আগে কিছু লিখুন
errors.body_too_long = আপনার বার্তাটি অনেক বড়
errors.title_is_required = অনুগ্রহ করে আপনার পোস্টের একটি শিরোনাম দিন
errors.title_too_long = আপনার শিরোনামটি অনেক বড়
errors.remote_failed = দূরবর্তী অনুরোধ ব্যর্থ হয়েছে
errors.service_unavailable = জমা দেওয়ার পরিষেবা সাময়িকভাবে অনুপলব্ধ। অনুগ্রহ করে পরে আবার চেষ্টা করুন।
errors.forum_not_found = ফোরাম পাওয়া যায়নি
errors.forum_not_found_in_directory = ডিরেক্টরিতে ফোরাম পাওয়া যায়নি
errors.not_allowed_to_post = পোস্ট করার অনুমতি নেই
errors.access_denied = অ্যাক্সেস অস্বীকৃত
errors.remote = দূরবর্তী সার্ভার অনুরোধটি সম্পন্ন করতে পারেনি
errors.unable_to_connect_to_server = সার্ভারের সাথে সংযোগ করতে অক্ষম
errors.invalid_post_id = অবৈধ পোস্ট ID
errors.invalid_title = অবৈধ শিরোনাম
errors.invalid_body = অবৈধ বিষয়বস্তু
errors.invalid_id = অবৈধ ID

attachment.errors.denied = অ্যাক্সেস অস্বীকৃত
attachment.errors.not_found = সংযুক্তি পাওয়া যায়নি
attachment.errors.unavailable = সংযুক্তি সাময়িকভাবে অনুপলব্ধ
