[labels]
app.name = Air
errors.identity_changed = আপনার অ্যাকাউন্ট পরিবর্তিত হয়েছে। সংরক্ষণের আগে পুনরায় লোড করুন।
errors.invalid_request = অবৈধ অনুরোধ
errors.missing_field = আবশ্যক ক্ষেত্র অনুপস্থিত
errors.not_found = পাওয়া যায়নি
errors.not_logged_in = চালিয়ে যেতে সাইন ইন করুন

attachment.errors.denied = অ্যাক্সেস অস্বীকৃত
attachment.errors.not_found = Attachment পাওয়া যায়নি
attachment.errors.unavailable = সংযুক্তি সাময়িকভাবে অনুপলব্ধ
