[labels]
app.name = Air
errors.identity_changed = Vaš račun je promijenjen. Ponovo učitajte prije spremanja.
errors.invalid_request = Nevažeći zahtjev
errors.missing_field = Nedostaje obavezno polje
errors.not_found = Nije pronađeno
errors.not_logged_in = Prijavite se za nastavak
errors.body_is_required = Napišite nešto prije slanja
errors.body_too_long = Vaša poruka je predugačka
errors.title_is_required = Unesite naslov objave
errors.title_too_long = Vaš naslov je predugačak
errors.remote_failed = Udaljeni zahtjev nije uspio
errors.service_unavailable = Usluga za slanje trenutno nije dostupna. Molimo pokušajte ponovo kasnije.
errors.forum_not_found = Forum nije pronađen
errors.forum_not_found_in_directory = Forum nije pronađen u direktoriju
errors.not_allowed_to_post = Nije dozvoljeno objavljivanje
errors.access_denied = Pristup odbijen
errors.remote = Udaljeni server nije mogao dovršiti zahtjev
errors.unable_to_connect_to_server = Nije moguće povezati se sa serverom
errors.invalid_post_id = Nevažeći ID objave
errors.invalid_title = Nevažeći naslov
errors.invalid_body = Nevažeći sadržaj
errors.invalid_id = Nevažeći ID

attachment.errors.denied = Pristup odbijen
attachment.errors.not_found = Prilog nije pronađen
attachment.errors.unavailable = Prilog je privremeno nedostupan
