[labels]
app.name = Air
errors.identity_changed = هەژمارەکەت گۆڕا. پێش پاشەکەوتکردن دووبارە بارکە.
errors.invalid_request = داواکاری نادروست
errors.missing_field = خانەی پێویست بەردەست نییە
errors.not_found = نەدۆزرایەوە
errors.not_logged_in = بۆ بەردەوامبوون بچۆ ژوورەوە
