[labels]
app.name = Air
errors.identity_changed = هەژمارەکەت گۆڕا. پێش پاشەکەوتکردن دووبارە بارکە.
errors.invalid_request = داواکاری نادروست
errors.missing_field = خانەی پێویست بەردەست نییە
errors.not_found = نەدۆزرایەوە
errors.not_logged_in = بۆ بەردەوامبوون بچۆ ژوورەوە
errors.body_is_required = تکایە پێش ناردن شتێک بنووسە
errors.body_too_long = نامەکەت زۆر درێژە
errors.title_is_required = تکایە ناونیشانێک بدە بە بابەتەکەت
errors.title_too_long = ناونیشانەکەت زۆر درێژە
errors.remote_failed = داواکاری دوور سەرکەوتوو نەبوو
errors.service_unavailable = خزمەتگوزاری ناردن بۆ ماوەیەکی کاتی بەردەست نییە. تکایە دواتر دووبارە هەوڵ بدەرەوە.
errors.forum_not_found = فۆڕەم نەدۆزرایەوە
errors.forum_not_found_in_directory = فۆڕەم لە ڕێنماییدا نەدۆزرایەوە
errors.not_allowed_to_post = ڕێگە نەدراوە بۆ پۆستکردن
errors.access_denied = دەستڕاگەیشتن ڕەتکرایەوە
errors.remote = ڕاژەکاری دوور نەیتوانی داواکارییەکە تەواو بکات
errors.unable_to_connect_to_server = ناتوانرێت پەیوەندی بە ڕاژەوە بکرێت
errors.invalid_post_id = ناسنامەی پۆست نادروستە
errors.invalid_title = ناونیشانی نادروست
errors.invalid_body = ناوەڕۆک نادروستە
errors.invalid_id = ناسنامەی نادروست

attachment.errors.denied = دەستڕاگەیشتن ڕەتکرایەوە
attachment.errors.not_found = هاوپێچ نەدۆزرایەوە
attachment.errors.unavailable = هاوپێچ بۆ ماوەیەک بەردەست نییە
