[labels]
app.name = Air
errors.identity_changed = Váš účet se změnil. Před uložením stránku načtěte znovu.
errors.invalid_request = Neplatný požadavek
errors.missing_field = Chybí povinné pole
errors.not_found = Nenalezeno
errors.not_logged_in = Pokračujte přihlášením
errors.body_is_required = Před odesláním něco napište
errors.body_too_long = Vaše zpráva je příliš dlouhá
errors.title_is_required = Zadejte prosím název příspěvku
errors.title_too_long = Váš název je příliš dlouhý
errors.remote_failed = Vzdálený požadavek se nezdařil
errors.service_unavailable = Služba pro odesílání je dočasně nedostupná. Zkuste to prosím znovu později.
errors.forum_not_found = Fórum nenalezeno
errors.forum_not_found_in_directory = Fórum nenalezeno v adresáři
errors.not_allowed_to_post = Přidávání příspěvků není povoleno
errors.access_denied = Přístup odepřen
errors.remote = Vzdálený server nemohl dokončit požadavek
errors.unable_to_connect_to_server = Nelze se připojit k serveru
errors.invalid_post_id = Neplatné ID příspěvku
errors.invalid_title = Neplatný název
errors.invalid_body = Neplatné tělo
errors.invalid_id = Neplatné ID

attachment.errors.denied = Přístup odepřen
attachment.errors.not_found = Příloha nenalezena
attachment.errors.unavailable = Příloha je dočasně nedostupná
