[labels]
app.name = Air
errors.identity_changed = Mae eich cyfrif wedi newid. Ail-lwythwch cyn cadw.
errors.invalid_request = Cais annilys
errors.missing_field = Maes gofynnol ar goll
errors.not_found = Heb ei ganfod
errors.not_logged_in = Mewngofnodwch i barhau
