[labels]
app.name = Air
errors.identity_changed = Mae eich cyfrif wedi newid. Ail-lwythwch cyn cadw.
errors.invalid_request = Cais annilys
errors.missing_field = Maes gofynnol ar goll
errors.not_found = Heb ei ganfod
errors.not_logged_in = Mewngofnodwch i barhau
errors.body_is_required = Teipiwch rywbeth cyn cyflwyno
errors.body_too_long = Mae eich neges yn rhy hir
errors.title_is_required = Rhowch deitl i'ch post
errors.title_too_long = Mae eich teitl yn rhy hir
errors.remote_failed = Methodd y cais o bell
errors.service_unavailable = Nid yw'r gwasanaeth cyflwyno ar gael dros dro. Rhowch gynnig arall arni yn nes ymlaen.
errors.forum_not_found = Fforwm heb ei ganfod
errors.forum_not_found_in_directory = Fforwm heb ei ganfod yn y cyfeiriadur
errors.not_allowed_to_post = Ni chaniateir postio
errors.access_denied = Mynediad wedi'i wrthod
errors.remote = Ni allai'r gweinydd pell gwblhau'r cais
errors.unable_to_connect_to_server = Methu cysylltu â'r gweinydd
errors.invalid_post_id = ID postiad annilys
errors.invalid_title = Teitl annilys
errors.invalid_body = Corff annilys
errors.invalid_id = ID annilys

attachment.errors.denied = Mynediad wedi'i wrthod
attachment.errors.not_found = Atodiad heb ei ganfod
attachment.errors.unavailable = Atodiad ddim ar gael dros dro
