[labels]
app.name = Air
errors.identity_changed = Teie konto on muutunud. Laadige enne salvestamist uuesti.
errors.invalid_request = Vigane päring
errors.missing_field = Kohustuslik väli puudub
errors.not_found = Ei leitud
errors.not_logged_in = Jätkamiseks logige sisse
errors.body_is_required = Kirjuta midagi enne saatmist
errors.body_too_long = Sinu sõnum on liiga pikk
errors.title_is_required = Anna oma postitusele pealkiri
errors.title_too_long = Sinu pealkiri on liiga pikk
errors.remote_failed = Kaugpäring ebaõnnestus
errors.service_unavailable = Esitamisteenus on ajutiselt kättesaamatu. Palun proovige hiljem uuesti.
errors.forum_not_found = Foorumit ei leitud
errors.forum_not_found_in_directory = Foorumit ei leitud kataloogist
errors.not_allowed_to_post = Postitamine pole lubatud
errors.access_denied = Juurdepääs keelatud
errors.remote = Kaugserver ei suutnud päringut lõpule viia
errors.unable_to_connect_to_server = Serveriga ei õnnestu ühenduda
errors.invalid_post_id = Vigane postituse ID
errors.invalid_title = Vigane pealkiri
errors.invalid_body = Vigane sisu
errors.invalid_id = Vigane ID

attachment.errors.denied = Juurdepääs keelatud
attachment.errors.not_found = Manust ei leitud
attachment.errors.unavailable = Manus pole ajutiselt saadaval
