[labels]
app.name = Air
errors.identity_changed = Zure kontua aldatu da. Kargatu berriro gorde aurretik.
errors.invalid_request = Eskaera baliogabea
errors.missing_field = Nahitaezko eremua falta da
errors.not_found = Ez da aurkitu
errors.not_logged_in = Hasi saioa jarraitzeko
errors.body_is_required = Idatzi zerbait bidali aurretik
errors.body_too_long = Zure mezua luzeegia da
errors.title_is_required = Eman izenburua zure argitalpenari
errors.title_too_long = Zure izenburua luzeegia da
errors.remote_failed = Urruneko eskaerak huts egin du
errors.service_unavailable = Bidaltzeko zerbitzua aldi baterako ez dago erabilgarri. Saiatu berriro geroago.
errors.forum_not_found = Foroa ez da aurkitu
errors.forum_not_found_in_directory = Foroa ez da direktorioan aurkitu
errors.not_allowed_to_post = Ez duzu argitaratzeko baimenik
errors.access_denied = Sarbidea ukatua
errors.remote = Urruneko zerbitzariak ezin izan du eskaera osatu
errors.unable_to_connect_to_server = Ezin da zerbitzariarekin konektatu
errors.invalid_post_id = Argitalpen ID baliogabea
errors.invalid_title = Izenburu baliogabea
errors.invalid_body = Gorputz baliogabea
errors.invalid_id = ID baliogabea

attachment.errors.denied = Sarbidea ukatua
attachment.errors.not_found = Eranskina ez da aurkitu
attachment.errors.unavailable = Eranskina aldi baterako ez dago erabilgarri
