[labels]
app.name = Air
errors.identity_changed = حساب شما تغییر کرد. پیش از ذخیره دوباره بارگذاری کنید.
errors.invalid_request = درخواست نامعتبر
errors.missing_field = فیلد الزامی وجود ندارد
errors.not_found = پیدا نشد
errors.not_logged_in = برای ادامه وارد شوید
