[labels]
app.name = Air
errors.identity_changed = Tá do chuntas athraithe. Athluchtaigh sula sábhálann tú.
errors.invalid_request = Iarratas neamhbhailí
errors.missing_field = Réimse riachtanach ar iarraidh
errors.not_found = Níor aimsíodh
errors.not_logged_in = Sínigh isteach chun leanúint ar aghaidh
errors.body_is_required = Clóscríobh rud éigin sula seolfaidh tú
errors.body_too_long = Tá do theachtaireacht ró-fhada
errors.title_is_required = Tabhair teideal don phostáil
errors.title_too_long = Tá do theideal ró-fhada
errors.remote_failed = Theip ar iarratas cianda
errors.service_unavailable = Tá an tseirbhís aighneachta ar fáil go sealadach. Bain triail eile as ar ball.
errors.forum_not_found = Fóram gan aimsiú
errors.forum_not_found_in_directory = Fóram gan aimsiú san eolaire
errors.not_allowed_to_post = Gan cead postáil
errors.access_denied = Rochtain diúltaithe
errors.remote = Níorbh fhéidir leis an bhfreastalaí cianda an t-iarratas a chur i gcrích
errors.unable_to_connect_to_server = Ní féidir nascadh leis an bhfreastalaí
errors.invalid_post_id = ID poist neamhbhailí
errors.invalid_title = Teideal neamhbhailí
errors.invalid_body = Corp neamhbhailí
errors.invalid_id = ID neamhbhailí

attachment.errors.denied = Rochtain diúltaithe
attachment.errors.not_found = Ceangaltán gan aimsiú
attachment.errors.unavailable = Ceangaltán níl ar fáil go sealadach
