[labels]
app.name = Air
errors.identity_changed = Dh'atharraich an cunntas agad. Ath-luchdaich mus sàbhail thu.
errors.invalid_request = Iarrtas mì-dhligheach
errors.missing_field = Tha raon riatanach a dhìth
errors.not_found = Cha deach a lorg
errors.not_logged_in = Clàraich a-steach gus leantainn ort
