[labels]
app.name = Air
errors.identity_changed = Dh'atharraich an cunntas agad. Ath-luchdaich mus sàbhail thu.
errors.invalid_request = Iarrtas mì-dhligheach
errors.missing_field = Tha raon riatanach a dhìth
errors.not_found = Cha deach a lorg
errors.not_logged_in = Clàraich a-steach gus leantainn ort
errors.body_is_required = Sgrìobh rudeigin mus cuir thu a-steach e
errors.body_too_long = Tha an teachdaireachd agad ro fhada
errors.title_is_required = Thoir tiotal don phostadh agad
errors.title_too_long = Tha an tiotal agad ro fhada
errors.remote_failed = Dh'fhàillig an t-iarrtas iomallach
errors.service_unavailable = Chan eil an t-seirbheis tagraidh ri fhaighinn rè ùine. Feuch ris a-rithist an ceann tamaill.
errors.forum_not_found = Cha deach am fòraman a lorg
errors.forum_not_found_in_directory = Cha deach am fòraman a lorg san eòlaire
errors.not_allowed_to_post = Chan eil cead postachadh
errors.access_denied = Inntrigeadh air a dhiùltadh
errors.remote = Cha b' urrainn dhan fhrithealaiche chèin an t-iarrtas a choileanadh
errors.unable_to_connect_to_server = Cha b' urrainnear ceangal ris an fhrithealaiche
errors.invalid_post_id = ID puist mhì-dhligheach
errors.invalid_title = Tiotal mì-dhligheach
errors.invalid_body = Bodhaig mhì-dhligheach
errors.invalid_id = ID mì-dhligheach

attachment.errors.denied = Inntrigeadh air a dhiùltadh
attachment.errors.not_found = Cha deach an ceanglachan a lorg
attachment.errors.unavailable = Ceanglachan nach eil ri fhaighinn an-dràsta
