[labels]
app.name = Air
errors.identity_changed = Nde mba'ete oñemoambue. Emyanyhẽ jey eñongatu mboyve.
errors.invalid_request = Jerure ndoikóiva
errors.missing_field = Ndaipóri peteĩ campo tekotevẽva
errors.not_found = Ndojejuhúi
errors.not_logged_in = Eike resegui hag̃ua
errors.body_is_required = Embojuaju michĩmi detalle remondo mboyve
errors.body_too_long = Ne ñe'ẽmondo ipuku eterei
errors.title_is_required = Eme'ẽ peteĩ teratee ne marandúpe
errors.title_too_long = Ne teratee ipuku eterei
errors.remote_failed = Mombyry jerure ndoikói
errors.service_unavailable = Ñemondo servicio ndaipóri sapy'ami. Eha'ã jey ag̃amieve.
errors.forum_not_found = Ndojejuhúi foro
errors.forum_not_found_in_directory = Ndojejuhúi foro directorio-pe
errors.not_allowed_to_post = Ndoheja'i omoherakuã
errors.access_denied = Jeike noñemoneĩri
errors.remote = Mohendaha mombyrygua ndaikatúi omohu'ã jerure
errors.unable_to_connect_to_server = Ndaikatúi oñembojoaju mohendahápe
errors.invalid_post_id = ID marandu ndovaléi
errors.invalid_title = Teratee ndovaléi
errors.invalid_body = Jehaipyre ndovaléi
errors.invalid_id = ID ndovaléi

attachment.errors.denied = Jeike noñemoneĩri
attachment.errors.not_found = Ndojejuhúi adjunto
attachment.errors.unavailable = Adjunto noĩri ko'ág̃a
