[labels]
app.name = Air
errors.identity_changed = Nde mba'ete oñemoambue. Emyanyhẽ jey eñongatu mboyve.
errors.invalid_request = Jerure ndoikóiva
errors.missing_field = Oĩ tenda tekotevẽva ndaipóri
errors.not_found = Ndojejuhúi
errors.not_logged_in = Eike eku'e hag̃ua
errors.body_is_required = Embohasa mboyve ehai mba'e
errors.body_too_long = Nde marandu ipukueterei
errors.title_is_required = Eme'ẽ peteĩ tera ne mbohasa rehegua
errors.title_too_long = Nde téra ipukueterei
errors.remote_failed = Mombyry jerure ndoikói
errors.service_unavailable = Pe ñemondo mba'apoha ndaipóri sapy'aitérã. Eha'ã jey ag̃amieve.
errors.forum_not_found = Ndojejuhúi forum
errors.forum_not_found_in_directory = Ndojejuhúi forum directorio-pe
errors.not_allowed_to_post = Ndoheja'i oposta
errors.access_denied = Jeike noñemoneĩri
errors.remote = Pe servidor mombyry ndaikatúi omoĩmba pe jerure
errors.unable_to_connect_to_server = Ndaikatúi oñembojoaju servidor-pe
errors.invalid_post_id = ID post ndovaléi
errors.invalid_title = Título ndovaléi
errors.invalid_body = Rete ndovaléi
errors.invalid_id = ID ndovaléi

attachment.errors.denied = Jeike noñemoneĩri
attachment.errors.not_found = Ndojejuhúi jeity
attachment.errors.unavailable = Mbojoapy noĩri ko'ág̃a g̃uarã
