[labels]
app.name = Air
errors.identity_changed = Nde mba'ete oñemoambue. Emyanyhẽ jey eñongatu mboyve.
errors.invalid_request = Jerure ndoikóiva
errors.missing_field = Oĩ tenda tekotevẽva ndaipóri
errors.not_found = Ndojejuhúi
errors.not_logged_in = Eike eku'e hag̃ua

attachment.errors.denied = Ndojeheja jeike
attachment.errors.not_found = Ndojejuhúi jeity
attachment.errors.unavailable = Mbojoapy noĩri ko'ág̃a g̃uarã
