[labels]
app.name = Air
errors.identity_changed = તમારું ખાતું બદલાયું છે. સાચવતાં પહેલાં ફરી લોડ કરો.
errors.invalid_request = અમાન્ય વિનંતી
errors.missing_field = આવશ્યક ક્ષેત્ર ખૂટે છે
errors.not_found = મળ્યું નથી
errors.not_logged_in = ચાલુ રાખવા સાઇન ઇન કરો
errors.body_is_required = કૃપા કરીને સબમિટ કરતા પહેલા કંઈક લખો
errors.body_too_long = તમારો સંદેશ ખૂબ લાંબો છે
errors.title_is_required = કૃપા કરીને તમારી પોસ્ટને શીર્ષક આપો
errors.title_too_long = તમારું શીર્ષક ખૂબ લાંબું છે
errors.remote_failed = દૂરસ્થ વિનંતી નિષ્ફળ થઈ
errors.service_unavailable = સબમિશન સેવા હાલમાં અસ્થાયી રૂપે અનુપલબ્ધ છે. કૃપા કરીને થોડી વાર પછી ફરી પ્રયાસ કરો.
errors.forum_not_found = ફોરમ મળ્યું નથી
errors.forum_not_found_in_directory = ડિરેક્ટરીમાં ફોરમ મળ્યું નથી
errors.not_allowed_to_post = પોસ્ટ કરવાની મંજૂરી નથી
errors.access_denied = ઍક્સેસ નકારી
errors.remote = દૂરસ્થ સર્વર વિનંતી પૂર્ણ કરી શક્યું નથી
errors.unable_to_connect_to_server = સર્વર સાથે કનેક્ટ થવામાં અસમર્થ
errors.invalid_post_id = અમાન્ય પોસ્ટ ID
errors.invalid_title = અમાન્ય શીર્ષક
errors.invalid_body = અમાન્ય બોડી
errors.invalid_id = અમાન્ય ID

attachment.errors.denied = ઍક્સેસ નકારી
attachment.errors.not_found = એટેચમેન્ટ મળ્યું નથી
attachment.errors.unavailable = જોડાણ અસ્થાયી રૂપે અનુપલબ્ધ છે
