[labels]
app.name = Air
errors.identity_changed = Asusunka ya canza. Sake loda kafin ajiyewa.
errors.invalid_request = Buƙata mara inganci
errors.missing_field = Filin da ake buƙata ya ɓace
errors.not_found = Ba a samu ba
errors.not_logged_in = Shiga don ci gaba
errors.body_is_required = Don Allah a buga wani abu kafin a aika
errors.body_too_long = Saƙonka ya yi tsawo sosai
errors.title_is_required = Don Allah a ba da taken sakon ku
errors.title_too_long = Taken naka ya yi tsawo sosai
errors.remote_failed = Bukatar nesa ta gaza
errors.service_unavailable = Sabis ɗin ƙaddamarwa ba ya samuwa na ɗan lokaci. Da fatan za a sake gwadawa daga baya.
errors.forum_not_found = Ba a sami forum ba
errors.forum_not_found_in_directory = Ba a sami forum a directory ba
errors.not_allowed_to_post = Ba a yarda da post ba
errors.access_denied = An hana shiga
errors.remote = Sabar mai nisa ba ta iya kammala buƙatar ba
errors.unable_to_connect_to_server = Ba a iya haɗi da server ba
errors.invalid_post_id = ID na post bai inganta ba
errors.invalid_title = Take bai inganta ba
errors.invalid_body = Body bai inganta ba
errors.invalid_id = ID bai inganta ba

attachment.errors.denied = An hana shiga
attachment.errors.not_found = Ba a sami attachment ba
attachment.errors.unavailable = Abin haɗe ba ya samuwa na ɗan lokaci
