[labels]
app.name = Air
errors.identity_changed = आपका खाता बदल गया है। सहेजने से पहले पुनः लोड करें।
errors.invalid_request = अमान्य अनुरोध
errors.missing_field = आवश्यक फ़ील्ड अनुपस्थित है
errors.not_found = नहीं मिला
errors.not_logged_in = जारी रखने के लिए साइन इन करें
errors.body_is_required = कृपया सबमिट करने से पहले कुछ लिखें
errors.body_too_long = आपका संदेश बहुत लंबा है
errors.title_is_required = कृपया अपनी पोस्ट को एक शीर्षक दें
errors.title_too_long = आपका शीर्षक बहुत लंबा है
errors.remote_failed = दूरस्थ अनुरोध विफल हुआ
errors.service_unavailable = सबमिशन सेवा अस्थायी रूप से अनुपलब्ध है। कृपया बाद में फिर से प्रयास करें।
errors.forum_not_found = फ़ोरम नहीं मिला
errors.forum_not_found_in_directory = डायरेक्टरी में फ़ोरम नहीं मिला
errors.not_allowed_to_post = पोस्ट करने की अनुमति नहीं
errors.access_denied = एक्सेस अस्वीकृत
errors.remote = दूरस्थ सर्वर अनुरोध पूरा नहीं कर सका
errors.unable_to_connect_to_server = सर्वर से कनेक्ट करने में असमर्थ
errors.invalid_post_id = अमान्य पोस्ट ID
errors.invalid_title = अमान्य शीर्षक
errors.invalid_body = अमान्य बॉडी
errors.invalid_id = अमान्य ID

attachment.errors.denied = एक्सेस अस्वीकृत
attachment.errors.not_found = अटैचमेंट नहीं मिला
attachment.errors.unavailable = अनुलग्नक अस्थायी रूप से अनुपलब्ध है
