[labels]
app.name = Air
errors.identity_changed = Vaš račun je promijenjen. Ponovno učitajte prije spremanja.
errors.invalid_request = Nevažeći zahtjev
errors.missing_field = Nedostaje obavezno polje
errors.not_found = Nije pronađeno
errors.not_logged_in = Prijavite se za nastavak
