[labels]
app.name = Air
errors.identity_changed = Ձեր հաշիվը փոխվել է։ Վերբեռնեք նախքան պահելը։
errors.invalid_request = Անվավեր հարցում
errors.missing_field = Պարտադիր դաշտը բացակայում է
errors.not_found = Չի գտնվել
errors.not_logged_in = Մուտք գործեք շարունակելու համար
