[labels]
app.name = Air
errors.identity_changed = Ձեր հաշիվը փոխվել է։ Վերբեռնեք նախքան պահելը։
errors.invalid_request = Անվավեր հարցում
errors.missing_field = Պարտադիր դաշտը բացակայում է
errors.not_found = Չի գտնվել
errors.not_logged_in = Մուտք գործեք շարունակելու համար
errors.body_is_required = Խնդրում ենք գրել ինչ-որ բան՝ նախքան ուղարկելը
errors.body_too_long = Ձեր հաղորդագրությունը չափազանց երկար է
errors.title_is_required = Խնդրում ենք ձեր գրառմանը վերնագիր տալ
errors.title_too_long = Ձեր վերնագիրը չափազանց երկար է
errors.remote_failed = Հեռակա հարցումը ձախողվեց
errors.service_unavailable = Ներկայացման ծառայությունը ժամանակավորապես անհասանելի է: Խնդրում ենք փորձել կրկին ավելի ուշ:
errors.forum_not_found = Ֆորումը չի գտնվել
errors.forum_not_found_in_directory = Ֆորումը չի գտնվել ցուցակում
errors.not_allowed_to_post = Չի թույլատրվում գրառել
errors.access_denied = Մուտքը մերժված է
errors.remote = Հեռավոր սերվերը չկարողացավ ավարտել հարցումը
errors.unable_to_connect_to_server = Չհաջողվեց միանալ սերվերին
errors.invalid_post_id = Անվավեր գրառման ID
errors.invalid_title = Անվավեր վերնագիր
errors.invalid_body = Անվավեր մարմին
errors.invalid_id = Անվավեր ID

attachment.errors.denied = Մուտքը մերժված է
attachment.errors.not_found = Կցորդը չի գտնվել
attachment.errors.unavailable = Կցորդը ժամանակավորապես հասանելի չէ
