[labels]
app.name = Air
errors.identity_changed = アカウントが変更されました。保存する前に再読み込みしてください。
errors.invalid_request = リクエストが無効です
errors.missing_field = 必須項目が入力されていません
errors.not_found = 見つかりません
errors.not_logged_in = 続行するにはサインインしてください
errors.body_is_required = 送信する前に何か入力してください
errors.body_too_long = メッセージが長すぎます
errors.title_is_required = 投稿にタイトルを付けてください
errors.title_too_long = タイトルが長すぎます
errors.remote_failed = リモート要求に失敗しました
errors.service_unavailable = 送信サービスは一時的にご利用いただけません。しばらくしてからもう一度お試しください。
errors.forum_not_found = フォーラムが見つかりません
errors.forum_not_found_in_directory = ディレクトリにフォーラムが見つかりません
errors.not_allowed_to_post = 投稿は許可されていません
errors.access_denied = アクセスが拒否されました
errors.remote = リモートサーバーはリクエストを完了できませんでした
errors.unable_to_connect_to_server = サーバーに接続できません
errors.invalid_post_id = 投稿IDが無効です
errors.invalid_title = タイトルが無効です
errors.invalid_body = 本文が無効です
errors.invalid_id = ID が無効です

attachment.errors.denied = アクセスが拒否されました
attachment.errors.not_found = 添付ファイルが見つかりません
attachment.errors.unavailable = 添付ファイルは一時的に利用できません
