[labels]
app.name = Air
errors.identity_changed = Akun sampeyan owah. Muat maneh sadurunge nyimpen.
errors.invalid_request = Panjaluk ora sah
errors.missing_field = Kolom wajib ora ana
errors.not_found = Ora ditemokake
errors.not_logged_in = Mlebu kanggo nerusake
errors.body_is_required = Mangga ketik soklah sadurunge ngirim
errors.body_too_long = Pesen sampeyan kedawan
errors.title_is_required = Mangga wenehi judhul postingan sampeyan
errors.title_too_long = Judul sampeyan kedawan
errors.remote_failed = Panyuwunan adoh gagal
errors.service_unavailable = Layanan kirim kanggo sawetara wektu ora kasedhiya. Mangga coba maneh mengko.
errors.forum_not_found = Forum ora ketemu
errors.forum_not_found_in_directory = Forum ora ketemu ing direktori
errors.not_allowed_to_post = Ora diijini posting
errors.access_denied = Akses ditolak
errors.remote = Server adoh ora bisa ngrampungake panjaluk
errors.unable_to_connect_to_server = Ora bisa nyambung menyang server
errors.invalid_post_id = ID post ora sah
errors.invalid_title = Judul ora sah
errors.invalid_body = Isi ora sah
errors.invalid_id = ID ora sah

attachment.errors.denied = Akses ditolak
attachment.errors.not_found = Lampiran ora ketemu
attachment.errors.unavailable = Lampiran sauntara ora kasedhiya
