[labels]
app.name = Air
errors.identity_changed = თქვენი ანგარიში შეიცვალა. შენახვამდე გადატვირთეთ.
errors.invalid_request = არასწორი მოთხოვნა
errors.missing_field = სავალდებულო ველი აკლია
errors.not_found = ვერ მოიძებნა
errors.not_logged_in = გასაგრძელებლად შედით
errors.body_is_required = გთხოვთ, გაგზავნამდე რაიმე აკრიფოთ
errors.body_too_long = თქვენი შეტყობინება ძალიან გრძელია
errors.title_is_required = გთხოვთ, თქვენს პოსტს სათაური დაარქვათ
errors.title_too_long = თქვენი სათაური ძალიან გრძელია
errors.remote_failed = დისტანციური მოთხოვნა ვერ შესრულდა
errors.service_unavailable = გაგზავნის სერვისი დროებით მიუწვდომელია. გთხოვთ, სცადოთ მოგვიანებით.
errors.forum_not_found = ფორუმი ვერ მოიძებნა
errors.forum_not_found_in_directory = ფორუმი დირექტორიაში ვერ მოიძებნა
errors.not_allowed_to_post = პოსტირება არ არის დაშვებული
errors.access_denied = წვდომა უარყოფილია
errors.remote = დაშორებულმა სერვერმა ვერ შეასრულა მოთხოვნა
errors.unable_to_connect_to_server = სერვერთან კავშირი შეუძლებელია
errors.invalid_post_id = არასწორი პოსტის ID
errors.invalid_title = არასწორი სათაური
errors.invalid_body = არასწორი ტექსტი
errors.invalid_id = არასწორი ID

attachment.errors.denied = წვდომა უარყოფილია
attachment.errors.not_found = დანართი ვერ მოიძებნა
attachment.errors.unavailable = დანართი დროებით მიუწვდომელია
