[labels]
app.name = Air
errors.identity_changed = គណនីរបស់អ្នកបានផ្លាស់ប្តូរ។ ផ្ទុកឡើងវិញមុនពេលរក្សាទុក។
errors.invalid_request = សំណើមិនត្រឹមត្រូវ
errors.missing_field = បាត់វាលដែលទាមទារ
errors.not_found = រកមិនឃើញ
errors.not_logged_in = ចូលដើម្បីបន្ត
errors.body_is_required = សូមវាយអ្វីមួយមុនពេលដាក់ស្នើ
errors.body_too_long = សាររបស់អ្នកវែងពេក
errors.title_is_required = សូមដាក់ចំណងជើងឱ្យការបង្ហោះរបស់អ្នក
errors.title_too_long = ចំណងជើងរបស់អ្នកវែងពេក
errors.remote_failed = សំណើពីចម្ងាយបានបរាជ័យ
errors.service_unavailable = សេវាដាក់ស្នើមិនអាចប្រើបានជាបណ្ដោះអាសន្ន។ សូមព្យាយាមម្ដងទៀតនៅពេលក្រោយ។
errors.forum_not_found = រកមិនឃើញវេទិកា
errors.forum_not_found_in_directory = រកមិនឃើញវេទិកាក្នុងថត
errors.not_allowed_to_post = មិនអនុញ្ញាតឱ្យបង្ហោះ
errors.access_denied = ការចូលប្រើត្រូវបានបដិសេធ
errors.remote = ម៉ាស៊ីនមេពីចម្ងាយមិនអាចបញ្ចប់សំណើបានទេ
errors.unable_to_connect_to_server = មិនអាចតភ្ជាប់ទៅ server
errors.invalid_post_id = ID ប្រកាសមិនត្រឹមត្រូវ
errors.invalid_title = ចំណងជើងមិនត្រឹមត្រូវ
errors.invalid_body = ខ្លឹមសារមិនត្រឹមត្រូវ
errors.invalid_id = ID មិនត្រឹមត្រូវ

attachment.errors.denied = ការចូលប្រើត្រូវបានបដិសេធ
attachment.errors.not_found = រកមិនឃើញឯកសារភ្ជាប់
attachment.errors.unavailable = ឯកសារភ្ជាប់មិនអាចប្រើបានបណ្ដោះអាសន្ន
