[labels]
app.name = Air
errors.identity_changed = ನಿಮ್ಮ ಖಾತೆ ಬದಲಾಗಿದೆ. ಉಳಿಸುವ ಮೊದಲು ಮರುಲೋಡ್ ಮಾಡಿ.
errors.invalid_request = ಅಮಾನ್ಯ ವಿನಂತಿ
errors.missing_field = ಅಗತ್ಯ ಕ್ಷೇತ್ರ ಕಾಣೆಯಾಗಿದೆ
errors.not_found = ಕಂಡುಬಂದಿಲ್ಲ
errors.not_logged_in = ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ
errors.body_is_required = ದಯವಿಟ್ಟು ಸಲ್ಲಿಸುವ ಮೊದಲು ಏನಾದರೂ ಟೈಪ್ ಮಾಡಿ
errors.body_too_long = ನಿಮ್ಮ ಸಂದೇಶವು ತುಂಬಾ ಉದ್ದವಾಗಿದೆ
errors.title_is_required = ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೋಸ್ಟ್‌ಗೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ
errors.title_too_long = ನಿಮ್ಮ ಶೀರ್ಷಿಕೆ ತುಂಬಾ ಉದ್ದವಾಗಿದೆ
errors.remote_failed = ರಿಮೋಟ್ ವಿನಂತಿ ವಿಫಲವಾಗಿದೆ
errors.service_unavailable = ಸಲ್ಲಿಕೆ ಸೇವೆ ತಾತ್ಕಾಲಿಕವಾಗಿ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.
errors.forum_not_found = ಫೋರಂ ಸಿಗಲಿಲ್ಲ
errors.forum_not_found_in_directory = ಡೈರೆಕ್ಟರಿಯಲ್ಲಿ ಫೋರಂ ಸಿಗಲಿಲ್ಲ
errors.not_allowed_to_post = ಪೋಸ್ಟ್ ಮಾಡಲು ಅನುಮತಿ ಇಲ್ಲ
errors.access_denied = ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ
errors.remote = ದೂರದ ಸರ್ವರ್ ವಿನಂತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ
errors.unable_to_connect_to_server = ಸರ್ವರ್‌ಗೆ ಕನೆಕ್ಟ್ ಆಗಲಾಗಲಿಲ್ಲ
errors.invalid_post_id = ಅಮಾನ್ಯ ಪೋಸ್ಟ್ ID
errors.invalid_title = ಅಮಾನ್ಯ ಶೀರ್ಷಿಕೆ
errors.invalid_body = ಅಮಾನ್ಯ ಬಾಡಿ
errors.invalid_id = ಅಮಾನ್ಯ ID

attachment.errors.denied = ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ
attachment.errors.not_found = ಲಗತ್ತು ಸಿಗಲಿಲ್ಲ
attachment.errors.unavailable = ಲಗತ್ತು ತಾತ್ಕಾಲಿಕವಾಗಿ ಲಭ್ಯವಿಲ್ಲ
