[labels]
app.name = Air
errors.identity_changed = Hesabê te guherî. Berî tomarkirinê ji nû ve bar bike.
errors.invalid_request = Daxwaza nederbasdar
errors.missing_field = Qada pêwîst kêm e
errors.not_found = Nehat dîtin
errors.not_logged_in = Ji bo berdewamkirinê têkeve
errors.body_is_required = Berî şandinê tiştekî binivîse
errors.body_too_long = Peyama te pir dirêj e
errors.title_is_required = Ji kerema xwe sernavekê bide nivîsa xwe
errors.title_too_long = Sernavê te pir dirêj e
errors.remote_failed = Daxwaza jixwerû têk çû
errors.service_unavailable = Karûbarê şandinê demkî ne berdest e. Ji kerema xwe paşê dîsa biceribîne.
errors.forum_not_found = Forum nehat dîtin
errors.forum_not_found_in_directory = Forum di pelrêçê de nehat dîtin
errors.not_allowed_to_post = Postekirin nayê destûrkirin
errors.access_denied = Gihîştin hat redkirin
errors.remote = Servera dûr nekarî daxwazê temam bike
errors.unable_to_connect_to_server = Têkilî bi serverê re nayê damezrandin
errors.invalid_post_id = ID-ya posteyê nederbasdar
errors.invalid_title = Sernavê nederbasdar
errors.invalid_body = Naveroka nederbasdar
errors.invalid_id = ID-ya nederbasdar

attachment.errors.denied = Gihîştin hat redkirin
attachment.errors.not_found = Pêvek nehat dîtin
attachment.errors.unavailable = Pêvek demkî ne berdest e
