[labels]
app.name = Air
errors.identity_changed = Аккаунтуңуз өзгөрдү. Сактоодон мурун кайра жүктөңүз.
errors.invalid_request = Жараксыз сурам
errors.missing_field = Милдеттүү талаа жок
errors.not_found = Табылган жок
errors.not_logged_in = Улантуу үчүн кириңиз
errors.body_is_required = Жөнөтүүдөн мурун бир нерсе жазыңыз
errors.body_too_long = Билдирүүңүз өтө узун
errors.title_is_required = Постуңузга аталыш бериңиз
errors.title_too_long = Аталышыңыз өтө узун
errors.remote_failed = Алыскы суроо аткарылган жок
errors.service_unavailable = Жөнөтүү кызматы убактылуу жеткиликсиз. Кийинчерээк кайра аракет кылыңыз.
errors.forum_not_found = Форум табылган жок
errors.forum_not_found_in_directory = Каталогдон форум табылган жок
errors.not_allowed_to_post = Пост жайгаштырууга уруксат жок
errors.access_denied = Жетки четке кагылды
errors.remote = Алыскы сервер суроо-талапты аягына чыгара алган жок
errors.unable_to_connect_to_server = Серверге туташуу мүмкүн эмес
errors.invalid_post_id = Жараксыз пост ID си
errors.invalid_title = Жараксыз аталыш
errors.invalid_body = Жараксыз текст
errors.invalid_id = Жараксыз ID

attachment.errors.denied = Жетки четке кагылды
attachment.errors.not_found = Тиркеме табылган жок
attachment.errors.unavailable = Тиркеме убактылуу жеткиликсиз
