[labels]
app.name = Air
errors.identity_changed = Jūsų paskyra pasikeitė. Prieš išsaugodami įkelkite iš naujo.
errors.invalid_request = Netinkama užklausa
errors.missing_field = Trūksta privalomo lauko
errors.not_found = Nerasta
errors.not_logged_in = Prisijunkite, kad tęstumėte
errors.body_is_required = Prieš siųsdami ką nors įrašykite
errors.body_too_long = Jūsų žinutė per ilga
errors.title_is_required = Įveskite įrašo pavadinimą
errors.title_too_long = Jūsų pavadinimas per ilgas
errors.remote_failed = Nuotolinė užklausa nepavyko
errors.service_unavailable = Pateikimo paslauga laikinai nepasiekiama. Bandykite dar kartą vėliau.
errors.forum_not_found = Forumas nerastas
errors.forum_not_found_in_directory = Forumas kataloge nerastas
errors.not_allowed_to_post = Neleidžiama skelbti
errors.access_denied = Prieiga atmesta
errors.remote = Nuotolinis serveris negalėjo įvykdyti užklausos
errors.unable_to_connect_to_server = Nepavyko prisijungti prie serverio
errors.invalid_post_id = Netinkamas įrašo ID
errors.invalid_title = Netinkamas pavadinimas
errors.invalid_body = Netinkamas turinys
errors.invalid_id = Netinkamas ID

attachment.errors.denied = Prieiga atmesta
attachment.errors.not_found = Priedas nerastas
attachment.errors.unavailable = Priedas laikinai nepasiekiamas
