[labels]
app.name = Air
errors.identity_changed = Вашата сметка е променета. Вчитајте повторно пред зачувување.
errors.invalid_request = Неважечко барање
errors.missing_field = Недостига задолжително поле
errors.not_found = Не е пронајдено
errors.not_logged_in = Најавете се за да продолжите
errors.body_is_required = Напишете нешто пред да испратите
errors.body_too_long = Вашата порака е предолга
errors.title_is_required = Внесете наслов на објавата
errors.title_too_long = Вашиот наслов е предолг
errors.remote_failed = Далечинското барање не успеа
errors.service_unavailable = Услугата за поднесување привремено е недостапна. Обидете се повторно подоцна.
errors.forum_not_found = Форумот не е пронајден
errors.forum_not_found_in_directory = Форумот не е пронајден во директориумот
errors.not_allowed_to_post = Не е дозволено објавување
errors.access_denied = Пристапот е одбиен
errors.remote = Оддалечениот сервер не можеше да го заврши барањето
errors.unable_to_connect_to_server = Не може да се поврзе со серверот
errors.invalid_post_id = Невалидно ID на објавата
errors.invalid_title = Невалиден наслов
errors.invalid_body = Невалидна содржина
errors.invalid_id = Невалидно ID

attachment.errors.denied = Пристапот е одбиен
attachment.errors.not_found = Прилогот не е пронајден
attachment.errors.unavailable = Прилогот е привремено недостапен
