[labels]
app.name = Air
errors.identity_changed = നിങ്ങളുടെ അക്കൗണ്ട് മാറി. സംരക്ഷിക്കുന്നതിനു മുമ്പ് വീണ്ടും ലോഡ് ചെയ്യുക.
errors.invalid_request = അസാധുവായ അഭ്യർത്ഥന
errors.missing_field = ആവശ്യമായ ഫീൽഡ് ഇല്ല
errors.not_found = കണ്ടെത്തിയില്ല
errors.not_logged_in = തുടരാൻ സൈൻ ഇൻ ചെയ്യുക
errors.body_is_required = സമർപ്പിക്കുന്നതിന് മുമ്പ് എന്തെങ്കിലും ടൈപ്പ് ചെയ്യുക
errors.body_too_long = നിങ്ങളുടെ സന്ദേശം വളരെ നീളമുള്ളതാണ്
errors.title_is_required = നിങ്ങളുടെ പോസ്റ്റിന് ഒരു തലക്കെട്ട് നൽകുക
errors.title_too_long = നിങ്ങളുടെ തലക്കെട്ട് വളരെ നീളമുള്ളതാണ്
errors.remote_failed = റിമോട്ട് അഭ്യർത്ഥന പരാജയപ്പെട്ടു
errors.service_unavailable = സമർപ്പണ സേവനം താൽക്കാലികമായി ലഭ്യമല്ല. ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക.
errors.forum_not_found = ഫോറം കണ്ടെത്തിയില്ല
errors.forum_not_found_in_directory = ഡയറക്ടറിയിൽ ഫോറം കണ്ടെത്തിയില്ല
errors.not_allowed_to_post = പോസ്റ്റ് ചെയ്യാൻ അനുവാദമില്ല
errors.access_denied = ആക്സസ് നിരസിച്ചു
errors.remote = വിദൂര സെർവറിന് അഭ്യർത്ഥന പൂർത്തിയാക്കാൻ കഴിഞ്ഞില്ല
errors.unable_to_connect_to_server = സെർവറിലേക്ക് കണക്റ്റ് ചെയ്യാൻ കഴിയില്ല
errors.invalid_post_id = അസാധുവായ പോസ്റ്റ് ID
errors.invalid_title = അസാധുവായ ടൈറ്റിൽ
errors.invalid_body = അസാധുവായ ബോഡി
errors.invalid_id = അസാധുവായ ID

attachment.errors.denied = ആക്സസ് നിരസിച്ചു
attachment.errors.not_found = അറ്റാച്ച്മെന്റ് കണ്ടെത്തിയില്ല
attachment.errors.unavailable = അറ്റാച്ച്മെന്റ് താൽക്കാലികമായി ലഭ്യമല്ല
