[labels]
app.name = Air
errors.identity_changed = Таны бүртгэл өөрчлөгдсөн. Хадгалахаас өмнө дахин ачаална уу.
errors.invalid_request = Буруу хүсэлт
errors.missing_field = Заавал бөглөх талбар байхгүй
errors.not_found = Олдсонгүй
errors.not_logged_in = Үргэлжлүүлэхийн тулд нэвтэрнэ үү
errors.body_is_required = Илгээхээсээ өмнө ямар нэг зүйл бичнэ үү
errors.body_too_long = Таны мессеж хэт урт байна
errors.title_is_required = Бичлэгтээ гарчиг өгнө үү
errors.title_too_long = Таны гарчиг хэт урт байна
errors.remote_failed = Алсын хүсэлт амжилтгүй боллоо
errors.service_unavailable = Илгээх үйлчилгээ түр хугацаагаар боломжгүй байна. Дараа дахин оролдоно уу.
errors.forum_not_found = Форум олдсонгүй
errors.forum_not_found_in_directory = Лавлахаас форум олдсонгүй
errors.not_allowed_to_post = Пост бичих эрхгүй
errors.access_denied = Хандалт хориглогдсон
errors.remote = Алсын сервер хүсэлтийг гүйцээж чадсангүй
errors.unable_to_connect_to_server = Сервертэй холбогдох боломжгүй
errors.invalid_post_id = Буруу пост ID
errors.invalid_title = Буруу гарчиг
errors.invalid_body = Буруу агуулга
errors.invalid_id = Буруу ID

attachment.errors.denied = Хандалт хориглогдсон
attachment.errors.not_found = Хавсралт олдсонгүй
attachment.errors.unavailable = Хавсралт түр хугацаанд боломжгүй байна
