[labels]
app.name = Air
errors.identity_changed = तुमचे खाते बदलले आहे. जतन करण्यापूर्वी पुन्हा लोड करा.
errors.invalid_request = अवैध विनंती
errors.missing_field = आवश्यक फील्ड गहाळ आहे
errors.not_found = आढळले नाही
errors.not_logged_in = सुरू ठेवण्यासाठी साइन इन करा
errors.body_is_required = कृपया सबमिट करण्यापूर्वी काहीतरी टाइप करा
errors.body_too_long = तुमचा संदेश खूप मोठा आहे
errors.title_is_required = कृपया तुमच्या पोस्टला एक शीर्षक द्या
errors.title_too_long = तुमचे शीर्षक खूप मोठे आहे
errors.remote_failed = दूरस्थ विनंती अयशस्वी झाली
errors.service_unavailable = सबमिशन सेवा तात्पुरती उपलब्ध नाही. कृपया नंतर पुन्हा प्रयत्न करा.
errors.forum_not_found = फोरम सापडले नाही
errors.forum_not_found_in_directory = निर्देशिकेमध्ये फोरम सापडले नाही
errors.not_allowed_to_post = पोस्ट करण्याची परवानगी नाही
errors.access_denied = प्रवेश नाकारला
errors.remote = दूरस्थ सर्व्हर विनंती पूर्ण करू शकला नाही
errors.unable_to_connect_to_server = सर्व्हरशी कनेक्ट होऊ शकले नाही
errors.invalid_post_id = अवैध पोस्ट ID
errors.invalid_title = अवैध शीर्षक
errors.invalid_body = अवैध मजकूर
errors.invalid_id = अवैध ID

attachment.errors.denied = प्रवेश नाकारला
attachment.errors.not_found = संलग्नक सापडले नाही
attachment.errors.unavailable = संलग्नक तात्पुरते अनुपलब्ध आहे
