[labels]
app.name = Air
errors.identity_changed = Il-kont tiegħek inbidel. Erġa' agħbi qabel tissejvja.
errors.invalid_request = Talba mhix valida
errors.missing_field = Qasam obbligatorju nieqes
errors.not_found = Ma nstabx
errors.not_logged_in = Idħol biex tkompli
errors.body_is_required = Jekk jogħġbok ikteb xi ħaġa qabel ma tibgħat
errors.body_too_long = Il-messaġġ tiegħek huwa twil wisq
errors.title_is_required = Jekk jogħġbok agħti titlu lill-post tiegħek
errors.title_too_long = It-titlu tiegħek huwa twil wisq
errors.remote_failed = It-talba mill-bogħod falliet
errors.service_unavailable = Is-servizz tas-sottomissjoni mhux disponibbli temporanjament. Jekk jogħġbok erġa' pprova aktar tard.
errors.forum_not_found = Forum ma nstabx
errors.forum_not_found_in_directory = Forum ma nstabx fid-direttorju
errors.not_allowed_to_post = Mhux permess tippublishja
errors.access_denied = Aċċess miċħud
errors.remote = Is-server remot ma setax ilesti t-talba
errors.unable_to_connect_to_server = Ma jistax jikkonnettja mas-server
errors.invalid_post_id = ID tal-post mhux validu
errors.invalid_title = Titlu mhux validu
errors.invalid_body = Body mhux validu
errors.invalid_id = ID mhux validu

attachment.errors.denied = Aċċess miċħud
attachment.errors.not_found = Attachment ma nstabx
attachment.errors.unavailable = Anness mhux disponibbli temporanjament
