[labels]
app.name = Air
errors.identity_changed = သင့်အကောင့် ပြောင်းလဲသွားပါပြီ။ မသိမ်းမီ ပြန်လည်ဖွင့်ပါ။
errors.invalid_request = မမှန်ကန်သော တောင်းဆိုချက်
errors.missing_field = လိုအပ်သော အကွက် ပျောက်နေသည်
errors.not_found = ရှာမတွေ့ပါ
errors.not_logged_in = ဆက်လက်ရန် လက်မှတ်ထိုးဝင်ပါ
errors.body_is_required = မတင်သွင်းမီ တစ်ခုခု ရိုက်ထည့်ပါ
errors.body_too_long = သင့်စာသည် ရှည်လွန်းသည်
errors.title_is_required = သင့်ပို့စ်ကို ခေါင်းစဉ် ပေးပါ
errors.title_too_long = သင့်ခေါင်းစဉ်သည် ရှည်လွန်းသည်
errors.remote_failed = အဝေးထိန်းတောင်းဆိုမှု မအောင်မြင်ပါ
errors.service_unavailable = တင်သွင်းမှုဝန်ဆောင်မှုကို ယာယီအသုံးပြု၍မရပါ။ ကျေးဇူးပြု၍ နောက်မှ ထပ်စမ်းကြည့်ပါ။
errors.forum_not_found = ဖိုရမ် မတွေ့ပါ
errors.forum_not_found_in_directory = လမ်းညွှန် တွင် ဖိုရမ် မတွေ့ပါ
errors.not_allowed_to_post = ပို့စ် တင်ခွင့် မရှိပါ
errors.access_denied = ဝင်ရောက်ခွင့် ငြင်းပယ်ခံရသည်
errors.remote = အဝေးဆာဗာသည် တောင်းဆိုချက်ကို မပြီးမြောက်နိုင်ပါ
errors.unable_to_connect_to_server = Server နှင့် ချိတ်ဆက်၍မရပါ
errors.invalid_post_id = ပို့စ် ID မမှန်ကန်ပါ
errors.invalid_title = ခေါင်းစဉ် မမှန်ကန်ပါ
errors.invalid_body = စာကိုယ် မမှန်ကန်ပါ
errors.invalid_id = ID မမှန်ကန်ပါ

attachment.errors.denied = ဝင်ရောက်ခွင့် ငြင်းပယ်ခံရသည်
attachment.errors.not_found = ပူးတွဲဖိုင် မတွေ့ပါ
attachment.errors.unavailable = ပူးတွဲဖိုင် ယာယီမရနိုင်ပါ
