[labels]
app.name = Air
errors.identity_changed = तपाईंको खाता परिवर्तन भयो। सुरक्षित गर्नुअघि पुनः लोड गर्नुहोस्।
errors.invalid_request = अमान्य अनुरोध
errors.missing_field = आवश्यक फिल्ड छैन
errors.not_found = फेला परेन
errors.not_logged_in = जारी राख्न साइन इन गर्नुहोस्
errors.body_is_required = कृपया पेश गर्नु अघि केही टाइप गर्नुहोस्
errors.body_too_long = तपाईंको सन्देश धेरै लामो छ
errors.title_is_required = कृपया आफ्नो पोस्टलाई एउटा शीर्षक दिनुहोस्
errors.title_too_long = तपाईंको शीर्षक धेरै लामो छ
errors.remote_failed = टाढाको अनुरोध असफल भयो
errors.service_unavailable = पेस गर्ने सेवा अस्थायी रूपमा उपलब्ध छैन। कृपया पछि फेरि प्रयास गर्नुहोस्।
errors.forum_not_found = फोरम फेला परेन
errors.forum_not_found_in_directory = डाइरेक्टरीमा फोरम फेला परेन
errors.not_allowed_to_post = पोस्ट गर्न अनुमति छैन
errors.access_denied = पहुँच अस्वीकृत
errors.remote = टाढाको सर्भरले अनुरोध पूरा गर्न सकेन
errors.unable_to_connect_to_server = पहिचान सिर्जना गर्न असमर्थ
errors.invalid_post_id = अमान्य पोस्ट ID
errors.invalid_title = अमान्य शीर्षक
errors.invalid_body = अमान्य मुख्य पाठ
errors.invalid_id = अमान्य ID

attachment.errors.denied = पहुँच अस्वीकृत
attachment.errors.not_found = एट्याचमेन्ट फेला परेन
attachment.errors.unavailable = संलग्नक अस्थायी रूपमा उपलब्ध छैन
