[labels]
app.name = Air
errors.identity_changed = Uw account is gewijzigd. Herlaad voordat u opslaat.
errors.invalid_request = Ongeldig verzoek
errors.missing_field = Verplicht veld ontbreekt
errors.not_found = Niet gevonden
errors.not_logged_in = Meld u aan om door te gaan
errors.body_is_required = Typ iets voordat je verzendt
errors.body_too_long = Je bericht is te lang
errors.title_is_required = Geef je bericht een titel
errors.title_too_long = Je titel is te lang
errors.remote_failed = Externe aanvraag mislukt
errors.service_unavailable = De inzendingsdienst is tijdelijk niet beschikbaar. Probeer het later opnieuw.
errors.forum_not_found = Forum niet gevonden
errors.forum_not_found_in_directory = Forum niet gevonden in directory
errors.not_allowed_to_post = Berichten plaatsen niet toegestaan
errors.access_denied = Toegang geweigerd
errors.remote = De externe server kon het verzoek niet voltooien
errors.unable_to_connect_to_server = Kan geen verbinding maken met server
errors.invalid_post_id = Ongeldige bericht-ID
errors.invalid_title = Ongeldige titel
errors.invalid_body = Ongeldige inhoud
errors.invalid_id = Ongeldige ID

attachment.errors.denied = Toegang geweigerd
attachment.errors.not_found = Bijlage niet gevonden
attachment.errors.unavailable = Bijlage tijdelijk niet beschikbaar
