[labels]
app.name = Air
errors.identity_changed = Kontoen din er endra. Last inn på nytt før du lagrar.
errors.invalid_request = Ugyldig førespurnad
errors.missing_field = Obligatorisk felt manglar
errors.not_found = Ikkje funnen
errors.not_logged_in = Logg inn for å halde fram
errors.body_is_required = Legg til litt fleire detaljar før du sender inn
errors.body_too_long = Meldinga di er for lang
errors.title_is_required = Gje innlegget ditt ein tittel
errors.title_too_long = Tittelen din er for lang
errors.remote_failed = Fjernførespurnaden feila
errors.service_unavailable = Innsendingstenesta er mellombels utilgjengeleg. Prøv igjen seinare.
errors.forum_not_found = Fann ikkje forumet
errors.forum_not_found_in_directory = Fann ikkje forumet i katalogen
errors.not_allowed_to_post = Du har ikkje lov til å publisere
errors.access_denied = Tilgang nekta
errors.remote = Fjerntenaren kunne ikkje fullføre førespurnaden
errors.unable_to_connect_to_server = Klarte ikkje å kople til tenaren
errors.invalid_post_id = Ugyldig innleggs-ID
errors.invalid_title = Ugyldig tittel
errors.invalid_body = Ugyldig tekst
errors.invalid_id = Ugyldig ID

attachment.errors.denied = Tilgang nekta
attachment.errors.not_found = Fann ikkje vedlegget
attachment.errors.unavailable = Vedlegg er mellombels utilgjengeleg
