[labels]
app.name = Air
errors.identity_changed = Herregni kee jijjiirameera. Osoo hin olkaa'in irra deebi'ii fe'i.
errors.invalid_request = Gaaffii sirrii hin taane
errors.missing_field = Dirreen barbaachisaan hin jiru
errors.not_found = Hin argamne
errors.not_logged_in = Itti fufuuf seeni

attachment.errors.denied = Seensi dhorkamee jira
attachment.errors.not_found = Maxxansaan hin argamne
attachment.errors.unavailable = Miiltoon yeroof hin argamu
