[labels]
app.name = Air
errors.identity_changed = Herregni kee jijjiirameera. Osoo hin olkaa'in irra deebi'ii fe'i.
errors.invalid_request = Gaaffii sirrii hin taane
errors.missing_field = Dirreen barbaachisaan hin jiru
errors.not_found = Hin argamne
errors.not_logged_in = Itti fufuuf seeni
errors.body_is_required = Maaloo erguu dura waan tokko barreessi
errors.body_too_long = Ergaan kee baayʼee dheeraadha
errors.title_is_required = Maaloo barruu kee mata-duree itti kenni
errors.title_too_long = Mata duree kee baayʼee dheeraadha
errors.remote_failed = Gaaffiin fagoo hin milkoofne
errors.service_unavailable = Tajaajilli galmeessuu yeroof hin argamu. Maaloo booda irra deebi'ii yaali.
errors.forum_not_found = Foorumiin hin argamne
errors.forum_not_found_in_directory = Foorumiin galmee keessatti hin argamne
errors.not_allowed_to_post = Barreessuun hin hayyamamne
errors.access_denied = Seensi dhorkamee jira
errors.remote = Sarvariin fagoo gaaffii xumuruu hin dandeenye
errors.unable_to_connect_to_server = Sarvarii wajjin hidhamuu hin danda'amne
errors.invalid_post_id = ID barreeffamaa sirrii miti
errors.invalid_title = Mata dureen sirrii miti
errors.invalid_body = Qabiyyeen sirrii miti
errors.invalid_id = ID sirrii miti

attachment.errors.denied = Seensi dhorkamee jira
attachment.errors.not_found = Maxxansaan hin argamne
attachment.errors.unavailable = Miiltoon yeroof hin argamu
