[labels]
app.name = Air
errors.identity_changed = ਤੁਹਾਡਾ ਖਾਤਾ ਬਦਲ ਗਿਆ ਹੈ। ਸੰਭਾਲਣ ਤੋਂ ਪਹਿਲਾਂ ਮੁੜ ਲੋਡ ਕਰੋ।
errors.invalid_request = ਅਵੈਧ ਬੇਨਤੀ
errors.missing_field = ਲੋੜੀਂਦਾ ਖੇਤਰ ਗੁੰਮ ਹੈ
errors.not_found = ਨਹੀਂ ਮਿਲਿਆ
errors.not_logged_in = ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ
errors.body_is_required = ਕਿਰਪਾ ਕਰਕੇ ਜਮ੍ਹਾਂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਕੁਝ ਲਿਖੋ
errors.body_too_long = ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਬਹੁਤ ਲੰਮਾ ਹੈ
errors.title_is_required = ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਪੋਸਟ ਨੂੰ ਇੱਕ ਸਿਰਲੇਖ ਦਿਓ
errors.title_too_long = ਤੁਹਾਡਾ ਸਿਰਲੇਖ ਬਹੁਤ ਲੰਮਾ ਹੈ
errors.remote_failed = ਰਿਮੋਟ ਬੇਨਤੀ ਅਸਫਲ ਰਹੀ
errors.service_unavailable = ਸਬਮਿਸ਼ਨ ਸੇਵਾ ਅਸਥਾਈ ਤੌਰ 'ਤੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।
errors.forum_not_found = ਫੋਰਮ ਨਹੀਂ ਮਿਲਿਆ
errors.forum_not_found_in_directory = ਡਾਇਰੈਕਟਰੀ ਵਿੱਚ ਫੋਰਮ ਨਹੀਂ ਮਿਲਿਆ
errors.not_allowed_to_post = ਪੋਸਟ ਕਰਨ ਦੀ ਆਗਿਆ ਨਹੀਂ ਹੈ
errors.access_denied = ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ
errors.remote = ਰਿਮੋਟ ਸਰਵਰ ਬੇਨਤੀ ਪੂਰੀ ਨਹੀਂ ਕਰ ਸਕਿਆ
errors.unable_to_connect_to_server = ਸਰਵਰ ਨਾਲ ਜੁੜਨ ਵਿੱਚ ਅਸਮਰੱਥ
errors.invalid_post_id = ਅਵੈਧ ਪੋਸਟ ID
errors.invalid_title = ਅਵੈਧ ਸਿਰਲੇਖ
errors.invalid_body = ਅਵੈਧ ਬੌਡੀ
errors.invalid_id = ਅਵੈਧ ID

attachment.errors.denied = ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ
attachment.errors.not_found = ਅਟੈਚਮੈਂਟ ਨਹੀਂ ਮਿਲੀ
attachment.errors.unavailable = ਅਟੈਚਮੈਂਟ ਅਸਥਾਈ ਤੌਰ 'ਤੇ ਉਪਲਬਧ ਨਹੀਂ
