[labels]
app.name = Air
errors.identity_changed = Twoje konto uległo zmianie. Odśwież przed zapisaniem.
errors.invalid_request = Nieprawidłowe żądanie
errors.missing_field = Brak wymaganego pola
errors.not_found = Nie znaleziono
errors.not_logged_in = Zaloguj się, aby kontynuować
errors.body_is_required = Wpisz coś przed wysłaniem
errors.body_too_long = Twoja wiadomość jest za długa
errors.title_is_required = Nadaj swojemu wpisowi tytuł
errors.title_too_long = Twój tytuł jest za długi
errors.remote_failed = Żądanie zdalne nie powiodło się
errors.service_unavailable = Usługa przesyłania jest tymczasowo niedostępna. Spróbuj ponownie później.
errors.forum_not_found = Nie znaleziono forum
errors.forum_not_found_in_directory = Nie znaleziono forum w katalogu
errors.not_allowed_to_post = Nie można publikować
errors.access_denied = Odmowa dostępu
errors.remote = Zdalny serwer nie mógł zrealizować żądania
errors.unable_to_connect_to_server = Nie można połączyć się z serwerem
errors.invalid_post_id = Nieprawidłowy identyfikator wpisu
errors.invalid_title = Nieprawidłowy tytuł
errors.invalid_body = Nieprawidłowa treść
errors.invalid_id = Nieprawidłowe ID

attachment.errors.denied = Odmowa dostępu
attachment.errors.not_found = Nie znaleziono załącznika
attachment.errors.unavailable = Załącznik jest tymczasowo niedostępny
