[labels]
app.name = Air
errors.identity_changed = ستاسو حساب بدل شو. له خوندي کولو مخکې بیا پورته کړئ.
errors.invalid_request = ناسمه غوښتنه
errors.missing_field = اړین ډګر نشته
errors.not_found = ونه موندل شو
errors.not_logged_in = د دوام لپاره ننوځئ
errors.body_is_required = د سپارلو دمخه څه ولیکئ
errors.body_too_long = ستاسو پیغام ډېر اوږد دی
errors.title_is_required = خپلې لیکنې ته سرلیک ورکړئ
errors.title_too_long = ستاسو سرلیک ډېر اوږد دی
errors.remote_failed = د لرې غوښتنه ناکامه شوه
errors.service_unavailable = د سپارلو خدمت په لنډمهاله توګه شتون نلري. مهرباني وکړئ وروسته بیا هڅه وکړئ.
errors.forum_not_found = فورم ونه موندل شو
errors.forum_not_found_in_directory = فورم په لارښود کې ونه موندل شو
errors.not_allowed_to_post = د پوسټ کولو اجازه نشته
errors.access_denied = لاسرسی رد شو
errors.remote = لرې سرور ونه شو کولی غوښتنه بشپړه کړي
errors.unable_to_connect_to_server = سرور سره نه شي نښلیدلی
errors.invalid_post_id = ناسم د پوسټ ID
errors.invalid_title = ناسم سرلیک
errors.invalid_body = ناسم متن
errors.invalid_id = ناسم ID

attachment.errors.denied = لاسرسی رد شو
attachment.errors.not_found = ضمیمه ونه موندل شوه
attachment.errors.unavailable = ضمیمه د لنډ وخت لپاره نشته
