[labels]
app.name = Air
errors.identity_changed = ستاسو حساب بدل شو. له خوندي کولو مخکې بیا پورته کړئ.
errors.invalid_request = ناسمه غوښتنه
errors.missing_field = اړین ډګر نشته
errors.not_found = و نه موندل شو
errors.not_logged_in = د دوام لپاره ننوځئ
