[labels]
app.name = Air
errors.identity_changed = Cuentaykiqa tikrarqun. Waqaychanaykipaq ñawpaqta musuqmanta churay.
errors.invalid_request = Mana allin mañakuy
errors.missing_field = Necesitasqa cheqa ch'usaq
errors.not_found = Mana tarikunchu
errors.not_logged_in = Yaykuy qatinaykipaq
errors.body_is_required = Apachiy ñawpaq imallatapas qillqaykuy
errors.body_too_long = Willakuyniyki ancha suni
errors.title_is_required = Qillqasqaykiman huk sutita churay
errors.title_too_long = Sutiyki ancha suni
errors.remote_failed = Karu mañakuy mana atikurqachu
errors.service_unavailable = Apachina servisyuqa kunanqa mana atikunchu. Ama hina kaspa qhipaman watiqmanta yanapakuy.
errors.forum_not_found = Forum mana tarisqachu
errors.forum_not_found_in_directory = Directoriopi forum mana tarisqachu
errors.not_allowed_to_post = Postear mana saqisqachu
errors.access_denied = Yaykuy mana saqisqachu
errors.remote = Karu servidorqa mañakuyta manam tukuyta atirqachu
errors.unable_to_connect_to_server = Serverman mana tinkiy atikurqachu
errors.invalid_post_id = Mana valid post ID
errors.invalid_title = Mana valid título
errors.invalid_body = Mana valid cuerpo
errors.invalid_id = Mana valid ID

attachment.errors.denied = Yaykuy mana saqisqachu
attachment.errors.not_found = Attachment mana tarisqachu
attachment.errors.unavailable = Ratapasqa kunanpaq mana tarikunchu
