[labels]
app.name = Air
errors.identity_changed = Cuentaykiqa hukchakurqan. Waqaychanaykimanta ñawpaqta kutimanta cargay.
errors.invalid_request = Mana allin mañakuy
errors.missing_field = Necesitasqa campo mana kanchu
errors.not_found = Mana tarikunchu
errors.not_logged_in = Yaykuy qatinaykipaq
errors.body_is_required = Apachiyta manaraq ruwachkaspa aslla astawan detalleta yapay
errors.body_too_long = Willakuyniyki nishu suni
errors.title_is_required = Qillqaykiman huk sutinchayta churay
errors.title_too_long = Sutinchayniyki nishu suni
errors.remote_failed = Karu mañakuy mana atikurqachu
errors.service_unavailable = Apachina servicioqa kunanqa mana kanchu. Qhipaman kutimanta ruway.
errors.forum_not_found = Foro mana tarisqachu
errors.forum_not_found_in_directory = Directoriopi foro mana tarisqachu
errors.not_allowed_to_post = Qillqay mana saqisqachu
errors.access_denied = Yaykuy mana saqisqachu
errors.remote = Karu servidorqa mañakuyta manam tukuyta atirqachu
errors.unable_to_connect_to_server = Servidorman mana t'inkiy atikurqanchu
errors.invalid_post_id = Mana allin qillqa ID
errors.invalid_title = Mana allin sutinchay
errors.invalid_body = Mana allin qillqa
errors.invalid_id = Mana allin ID

attachment.errors.denied = Yaykuy mana saqisqachu
attachment.errors.not_found = Adjunto mana tarisqachu
attachment.errors.unavailable = Adjunto kunanpaq mana tarikunchu
