[labels]
app.name = Air
errors.identity_changed = Cuentaykiqa tikrarqun. Waqaychanaykipaq ñawpaqta musuqmanta churay.
errors.invalid_request = Mana allin mañakuy
errors.missing_field = Necesitasqa cheqa ch'usaq
errors.not_found = Mana tarisqachu
errors.not_logged_in = Yaykuy qatinaykipaq
