[labels]
app.name = Air
errors.identity_changed = توهانجو اڪائونٽ تبديل ٿي ويو. محفوظ ڪرڻ کان اڳ ٻيهر لوڊ ڪريو.
errors.invalid_request = غلط درخواست
errors.missing_field = ضروري خانو غائب آهي
errors.not_found = نه مليو
errors.not_logged_in = جاري رکڻ لاءِ سائن ان ڪريو
