[labels]
app.name = Air
errors.identity_changed = توهانجو اڪائونٽ تبديل ٿي ويو. محفوظ ڪرڻ کان اڳ ٻيهر لوڊ ڪريو.
errors.invalid_request = غلط درخواست
errors.missing_field = ضروري خانو غائب آهي
errors.not_found = نه مليو
errors.not_logged_in = جاري رکڻ لاءِ سائن ان ڪريو
errors.body_is_required = مهرباني ڪري جمع ڪرڻ کان اڳ ڪجهه لکو
errors.body_too_long = توهان جو پيغام تمام ڊگهو آهي
errors.title_is_required = مهرباني ڪري پنهنجي پوسٽ کي عنوان ڏيو
errors.title_too_long = توهان جو عنوان تمام ڊگهو آهي
errors.remote_failed = ريموٽ درخواست ناڪام ٿي
errors.service_unavailable = جمع ڪرائڻ جي خدمت عارضي طور تي دستياب ناهي. مهرباني ڪري پوءِ ٻيهر ڪوشش ڪريو.
errors.forum_not_found = فورم نه مليو
errors.forum_not_found_in_directory = ڊائريڪٽري ۾ فورم نه مليو
errors.not_allowed_to_post = پوسٽ ڪرڻ جي اجازت ناهي
errors.access_denied = رسائي رد ڪئي وئي
errors.remote = ريموٽ سرور درخواست مڪمل نه ڪري سگهيو
errors.unable_to_connect_to_server = سرور سان ڪنيڪٽ ٿيڻ ۾ ناڪامياب
errors.invalid_post_id = غلط پوسٽ ID
errors.invalid_title = غلط عنوان
errors.invalid_body = غلط متن
errors.invalid_id = غلط ID

attachment.errors.denied = رسائي رد ڪئي وئي
attachment.errors.not_found = منسلڪ نه مليو
attachment.errors.unavailable = منسلڪ عارضي طور دستياب ناهي
