[labels]
app.name = Air
errors.identity_changed = ඔබේ ගිණුම වෙනස් විය. සුරැකීමට පෙර නැවත පූරණය කරන්න.
errors.invalid_request = අවලංගු ඉල්ලීමකි
errors.missing_field = අවශ්‍ය ක්ෂේත්‍රය නොමැත
errors.not_found = හමු නොවීය
errors.not_logged_in = ඉදිරියට යාමට පුරන්න
