[labels]
app.name = Air
errors.identity_changed = ඔබේ ගිණුම වෙනස් විය. සුරැකීමට පෙර නැවත පූරණය කරන්න.
errors.invalid_request = අවලංගු ඉල්ලීමකි
errors.missing_field = අවශ්‍ය ක්ෂේත්‍රය නොමැත
errors.not_found = හමු නොවීය
errors.not_logged_in = ඉදිරියට යාමට පුරන්න
errors.body_is_required = කරුණාකර ඉදිරිපත් කිරීමට පෙර යමක් ටයිප් කරන්න
errors.body_too_long = ඔබේ පණිවිඩය දිගට වැඩියි
errors.title_is_required = කරුණාකර ඔබේ පළ කිරීමට මාතෘකාවක් දෙන්න
errors.title_too_long = ඔබේ මාතෘකාව දිගට වැඩියි
errors.remote_failed = දුරස්ථ ඉල්ලීම අසාර්ථකයි
errors.service_unavailable = ඉදිරිපත් කිරීමේ සේවාව තාවකාලිකව ලබා ගත නොහැක. කරුණාකර පසුව නැවත උත්සාහ කරන්න.
errors.forum_not_found = සංසදය සොයාගත නොහැකි විය
errors.forum_not_found_in_directory = නාමාවලියේ සංසදය සොයාගත නොහැකි විය
errors.not_allowed_to_post = පළ කිරීමට අවසර නැත
errors.access_denied = ප්‍රවේශය ප්‍රතික්ෂේප විය
errors.remote = දුරස්ථ සේවාදායකයට ඉල්ලීම සම්පූර්ණ කළ නොහැකි විය
errors.unable_to_connect_to_server = සේවාදායකයට සම්බන්ධ විය නොහැක
errors.invalid_post_id = වලංගු නොවන පළ කිරීම් ID
errors.invalid_title = වලංගු නොවන මාතෘකාව
errors.invalid_body = වලංගු නොවන අන්තර්ගතය
errors.invalid_id = වලංගු නොවන ID

attachment.errors.denied = ප්‍රවේශය ප්‍රතික්ෂේප විය
attachment.errors.not_found = ඇමුණුම සොයාගත නොහැකි විය
attachment.errors.unavailable = ඇමුණුම තාවකාලිකව නොමැත
