[labels]
app.name = Air
errors.identity_changed = Váš účet sa zmenil. Pred uložením stránku znova načítajte.
errors.invalid_request = Neplatná požiadavka
errors.missing_field = Chýba povinné pole
errors.not_found = Nenájdené
errors.not_logged_in = Pokračujte prihlásením
errors.body_is_required = Pred odoslaním niečo napíšte
errors.body_too_long = Vaša správa je príliš dlhá
errors.title_is_required = Zadajte názov príspevku
errors.title_too_long = Váš názov je príliš dlhý
errors.remote_failed = Vzdialená požiadavka zlyhala
errors.service_unavailable = Služba na odosielanie je dočasne nedostupná. Skúste to znova neskôr.
errors.forum_not_found = Fórum sa nenašlo
errors.forum_not_found_in_directory = Fórum sa v adresári nenašlo
errors.not_allowed_to_post = Nepovolené pridávať príspevky
errors.access_denied = Prístup zamietnutý
errors.remote = Vzdialený server nemohol dokončiť požiadavku
errors.unable_to_connect_to_server = Nepodarilo sa pripojiť k serveru
errors.invalid_post_id = Neplatné ID príspevku
errors.invalid_title = Neplatný názov
errors.invalid_body = Neplatný text
errors.invalid_id = Neplatné ID

attachment.errors.denied = Prístup zamietnutý
attachment.errors.not_found = Príloha sa nenašla
attachment.errors.unavailable = Príloha je dočasne nedostupná
