[labels]
app.name = Air
errors.identity_changed = Váš účet sa zmenil. Pred uložením stránku znova načítajte.
errors.invalid_request = Neplatná požiadavka
errors.missing_field = Chýba povinné pole
errors.not_found = Nenájdené
errors.not_logged_in = Pokračujte prihlásením
