[labels]
app.name = Air
errors.identity_changed = Vaš račun se je spremenil. Pred shranjevanjem znova naložite.
errors.invalid_request = Neveljavna zahteva
errors.missing_field = Manjka obvezno polje
errors.not_found = Ni najdeno
errors.not_logged_in = Prijavite se za nadaljevanje
errors.body_is_required = Pred pošiljanjem nekaj napišite
errors.body_too_long = Vaše sporočilo je predolgo
errors.title_is_required = Vnesite naslov objave
errors.title_too_long = Vaš naslov je predolg
errors.remote_failed = Oddaljena zahteva ni uspela
errors.service_unavailable = Storitev za oddajo je trenutno nedosegljiva. Poskusite znova pozneje.
errors.forum_not_found = Forum ni najden
errors.forum_not_found_in_directory = Forum ni najden v imeniku
errors.not_allowed_to_post = Ni dovoljeno objavljati
errors.access_denied = Dostop zavrnjen
errors.remote = Oddaljeni strežnik ni mogel dokončati zahteve
errors.unable_to_connect_to_server = Povezava s strežnikom ni mogoča
errors.invalid_post_id = Neveljaven ID objave
errors.invalid_title = Neveljaven naslov
errors.invalid_body = Neveljavno telo
errors.invalid_id = Neveljaven ID

attachment.errors.denied = Dostop zavrnjen
attachment.errors.not_found = Priloga ni najdena
attachment.errors.unavailable = Priloga je začasno nedosegljiva
