[labels]
app.name = Air
errors.identity_changed = Vaš račun se je spremenil. Pred shranjevanjem znova naložite.
errors.invalid_request = Neveljavna zahteva
errors.missing_field = Manjka obvezno polje
errors.not_found = Ni najdeno
errors.not_logged_in = Prijavite se za nadaljevanje
