[labels]
app.name = Air
errors.identity_changed = Ваш налог је промењен. Поново учитајте пре чувања.
errors.invalid_request = Неисправан захтев
errors.missing_field = Недостаје обавезно поље
errors.not_found = Није пронађено
errors.not_logged_in = Пријавите се да наставите
errors.body_is_required = Унесите нешто пре слања
errors.body_too_long = Ваша порука је предугачка
errors.title_is_required = Унесите наслов објаве
errors.title_too_long = Ваш наслов је предугачак
errors.remote_failed = Удаљени захтев није успео
errors.service_unavailable = Услуга за слање је тренутно недоступна. Покушајте поново касније.
errors.forum_not_found = Форум није пронађен
errors.forum_not_found_in_directory = Форум није пронађен у директоријуму
errors.not_allowed_to_post = Постављање није дозвољено
errors.access_denied = Приступ одбијен
errors.remote = Удаљени сервер није могао да заврши захтев
errors.unable_to_connect_to_server = Повезивање са сервером није могуће
errors.invalid_post_id = Неисправан ID поста
errors.invalid_title = Неисправан наслов
errors.invalid_body = Неисправно тело
errors.invalid_id = Неисправан ID

attachment.errors.denied = Приступ одбијен
attachment.errors.not_found = Прилог није пронађен
attachment.errors.unavailable = Прилог је привремено недоступан
