[labels]
app.name = Air
errors.identity_changed = Akun anjeun robih. Muat deui sateuacan nyimpen.
errors.invalid_request = Pamundut teu sah
errors.missing_field = Widang wajib teu aya
errors.not_found = Teu kapanggih
errors.not_logged_in = Lebet pikeun neruskeun
errors.body_is_required = Mangga ketik hiji hal saméméh ngirim
errors.body_too_long = Pesen anjeun panjang teuing
errors.title_is_required = Mangga pasihan judul kana kintunan anjeun
errors.title_too_long = Judul anjeun panjang teuing
errors.remote_failed = Pamundut jauh gagal
errors.service_unavailable = Layanan ngirim samentawis teu sayagi. Mangga cobian deui engké.
errors.forum_not_found = Forum teu kapanggih
errors.forum_not_found_in_directory = Forum teu kapanggih dina diréktori
errors.not_allowed_to_post = Teu diidinan ngirim pos
errors.access_denied = Aksés ditolak
errors.remote = Server jauh teu tiasa ngaréngsékeun paménta
errors.unable_to_connect_to_server = Teu bisa nyambung ka server
errors.invalid_post_id = ID pos teu sah
errors.invalid_title = Judul teu sah
errors.invalid_body = Badan teu sah
errors.invalid_id = ID teu sah

attachment.errors.denied = Aksés ditolak
attachment.errors.not_found = Lampiran teu kapanggih
attachment.errors.unavailable = Lampiran samentawis teu sayogi
