[labels]
app.name = Air
errors.identity_changed = உங்கள் கணக்கு மாறியுள்ளது. சேமிக்கும் முன் மீண்டும் ஏற்றவும்.
errors.invalid_request = தவறான கோரிக்கை
errors.missing_field = தேவையான புலம் இல்லை
errors.not_found = கிடைக்கவில்லை
errors.not_logged_in = தொடர உள்நுழையவும்
errors.body_is_required = சமர்ப்பிக்கும் முன் ஏதேனும் தட்டச்சு செய்யவும்
errors.body_too_long = உங்கள் செய்தி மிகவும் நீளமாக உள்ளது
errors.title_is_required = உங்கள் இடுகைக்கு ஒரு தலைப்பைக் கொடுக்கவும்
errors.title_too_long = உங்கள் தலைப்பு மிகவும் நீளமாக உள்ளது
errors.remote_failed = தொலைநிலை கோரிக்கை தோல்வியடைந்தது
errors.service_unavailable = சமர்ப்பிப்புச் சேவை தற்காலிகமாகக் கிடைக்கவில்லை. பிறகு மீண்டும் முயற்சிக்கவும்.
errors.forum_not_found = ஃபோரம் கிடைக்கவில்லை
errors.forum_not_found_in_directory = டைரக்டரியில் ஃபோரம் கிடைக்கவில்லை
errors.not_allowed_to_post = பதிவிட அனுமதிக்கப்படவில்லை
errors.access_denied = அணுகல் மறுக்கப்பட்டது
errors.remote = தொலைநிலை சேவையகத்தால் கோரிக்கையை நிறைவு செய்ய முடியவில்லை
errors.unable_to_connect_to_server = சர்வருடன் இணைக்க முடியவில்லை
errors.invalid_post_id = தவறான பதிவு ID
errors.invalid_title = தவறான தலைப்பு
errors.invalid_body = தவறான உள்ளடக்கம்
errors.invalid_id = தவறான ID

attachment.errors.denied = அணுகல் மறுக்கப்பட்டது
attachment.errors.not_found = இணைப்பு கிடைக்கவில்லை
attachment.errors.unavailable = இணைப்பு தற்காலிகமாக கிடைக்கவில்லை
