[labels]
app.name = Air
errors.identity_changed = మీ ఖాతా మారింది. సేవ్ చేయడానికి ముందు మళ్లీ లోడ్ చేయండి.
errors.invalid_request = చెల్లని అభ్యర్థన
errors.missing_field = అవసరమైన ఫీల్డ్ లేదు
errors.not_found = కనుగొనబడలేదు
errors.not_logged_in = కొనసాగించడానికి సైన్ ఇన్ చేయండి
