[labels]
app.name = Air
errors.identity_changed = మీ ఖాతా మారింది. సేవ్ చేయడానికి ముందు మళ్లీ లోడ్ చేయండి.
errors.invalid_request = చెల్లని అభ్యర్థన
errors.missing_field = అవసరమైన ఫీల్డ్ లేదు
errors.not_found = కనుగొనబడలేదు
errors.not_logged_in = కొనసాగించడానికి సైన్ ఇన్ చేయండి
errors.body_is_required = దయచేసి సమర్పించే ముందు ఏదైనా టైప్ చేయండి
errors.body_too_long = మీ సందేశం చాలా పొడవుగా ఉంది
errors.title_is_required = దయచేసి మీ పోస్ట్‌కు శీర్షికను ఇవ్వండి
errors.title_too_long = మీ శీర్షిక చాలా పొడవుగా ఉంది
errors.remote_failed = రిమోట్ అభ్యర్థన విఫలమైంది
errors.service_unavailable = సమర్పణ సేవ తాత్కాలికంగా అందుబాటులో లేదు. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి.
errors.forum_not_found = ఫోరమ్ కనుగొనబడలేదు
errors.forum_not_found_in_directory = డైరెక్టరీలో ఫోరమ్ కనుగొనబడలేదు
errors.not_allowed_to_post = పోస్ట్ చేయడానికి అనుమతించబడలేదు
errors.access_denied = యాక్సెస్ నిరాకరించబడింది
errors.remote = రిమోట్ సర్వర్ అభ్యర్థనను పూర్తి చేయలేకపోయింది
errors.unable_to_connect_to_server = సర్వర్‌కు కనెక్ట్ చేయడం సాధ్యం కాలేదు
errors.invalid_post_id = చెల్లని పోస్ట్ ID
errors.invalid_title = చెల్లని శీర్షిక
errors.invalid_body = చెల్లని బాడీ
errors.invalid_id = చెల్లని ID

attachment.errors.denied = యాక్సెస్ నిరాకరించబడింది
attachment.errors.not_found = అటాచ్‌మెంట్ కనుగొనబడలేదు
attachment.errors.unavailable = జోడింపు తాత్కాలికంగా అందుబాటులో లేదు
