[labels]
app.name = Air
errors.identity_changed = Ҳисоби шумо тағйир ёфт. Пеш аз захира кардан аз нав бор кунед.
errors.invalid_request = Дархости нодуруст
errors.missing_field = Майдони ҳатмӣ нест
errors.not_found = Ёфт нашуд
errors.not_logged_in = Барои идома ворид шавед
