[labels]
app.name = Air
errors.identity_changed = Ҳисоби шумо тағйир ёфт. Пеш аз захира кардан аз нав бор кунед.
errors.invalid_request = Дархости нодуруст
errors.missing_field = Майдони ҳатмӣ нест
errors.not_found = Ёфт нашуд
errors.not_logged_in = Барои идома ворид шавед
errors.body_is_required = Лутфан пеш аз фиристодан чизе нависед
errors.body_too_long = Паёми шумо хеле дароз аст
errors.title_is_required = Лутфан ба паёми худ сарлавҳа диҳед
errors.title_too_long = Сарлавҳаи шумо хеле дароз аст
errors.remote_failed = Дархости дурдаст ноком шуд
errors.service_unavailable = Хадамоти ирсол муваққатан дастрас нест. Лутфан баъдтар бори дигар кӯшиш кунед.
errors.forum_not_found = Форум ёфт нашуд
errors.forum_not_found_in_directory = Форум дар феҳрист ёфт нашуд
errors.not_allowed_to_post = Иҷозати фиристодан нест
errors.access_denied = Дастрасӣ рад карда шуд
errors.remote = Сервери дурдаст дархостро иҷро карда натавонист
errors.unable_to_connect_to_server = Пайвастан ба сервер имконнопазир аст
errors.invalid_post_id = ID-и паём нодуруст аст
errors.invalid_title = Сарлавҳа нодуруст аст
errors.invalid_body = Матн нодуруст аст
errors.invalid_id = ID нодуруст аст

attachment.errors.denied = Дастрасӣ рад карда шуд
attachment.errors.not_found = Замима ёфт нашуд
attachment.errors.unavailable = Замима муваққатан дастрас нест
