[labels]
app.name = Air
errors.identity_changed = Hasabyňyz üýtgedi. Ýatda saklamazdan öň gaýtadan ýükläň.
errors.invalid_request = Nädogry haýyş
errors.missing_field = Hökmany meýdan ýok
errors.not_found = Tapylmady
errors.not_logged_in = Dowam etmek üçin giriň
errors.body_is_required = Ibermezden öň bir zat ýazyň
errors.body_too_long = Habaryňyz gaty uzyn
errors.title_is_required = Postuňyza at beriň
errors.title_too_long = Sözbaşyňyz gaty uzyn
errors.remote_failed = Uzakdaky haýyş şowsuz boldy
errors.service_unavailable = Ibermek hyzmaty wagtlaýyn elýeterli däl. Soňra ýene synanyşyň.
errors.forum_not_found = Forum tapylmady
errors.forum_not_found_in_directory = Forum katalogda tapylmady
errors.not_allowed_to_post = Ýazga rugsat ýok
errors.access_denied = Giriş ret edildi
errors.remote = Uzakdaky server haýyşy tamamlap bilmedi
errors.unable_to_connect_to_server = Serwere birikdirip bolmady
errors.invalid_post_id = Nädogry ýazgy ID
errors.invalid_title = Nädogry at
errors.invalid_body = Nädogry mazmun
errors.invalid_id = Nädogry ID

attachment.errors.denied = Giriş ret edildi
attachment.errors.not_found = Goşundy tapylmady
attachment.errors.unavailable = Goşundy wagtlaýyn elýeterli däl
