[labels]
app.name = Air
errors.identity_changed = Nagbago ang iyong account. I-reload bago mag-save.
errors.invalid_request = Hindi wastong kahilingan
errors.missing_field = Kulang ang kinakailangang field
errors.not_found = Hindi nahanap
errors.not_logged_in = Mag-sign in para magpatuloy
errors.body_is_required = Mangyaring mag-type ng kahit ano bago isumite
errors.body_too_long = Masyadong mahaba ang iyong mensahe
errors.title_is_required = Mangyaring bigyan ng pamagat ang iyong post
errors.title_too_long = Masyadong mahaba ang iyong pamagat
errors.remote_failed = Nabigo ang malayong kahilingan
errors.service_unavailable = Pansamantalang hindi available ang serbisyo sa pagsusumite. Pakisubukang muli mamaya.
errors.forum_not_found = Hindi nakita ang forum
errors.forum_not_found_in_directory = Hindi nakita ang forum sa directory
errors.not_allowed_to_post = Hindi pinapayagang mag-post
errors.access_denied = Tinanggihan ang access
errors.remote = Hindi makumpleto ng malayong server ang kahilingan
errors.unable_to_connect_to_server = Hindi makakonekta sa server
errors.invalid_post_id = Hindi valid ang post ID
errors.invalid_title = Hindi valid ang title
errors.invalid_body = Hindi valid ang body
errors.invalid_id = Hindi valid ang ID

attachment.errors.denied = Tinanggihan ang access
attachment.errors.not_found = Hindi nakita ang attachment
attachment.errors.unavailable = Pansamantalang hindi magagamit ang kalakip
