[labels]
app.name = Air
errors.identity_changed = Ваш обліковий запис змінився. Перезавантажте перед збереженням.
errors.invalid_request = Недійсний запит
errors.missing_field = Відсутнє обов'язкове поле
errors.not_found = Не знайдено
errors.not_logged_in = Увійдіть, щоб продовжити
errors.body_is_required = Введіть текст перед надсиланням
errors.body_too_long = Ваше повідомлення задовге
errors.title_is_required = Додайте заголовок до публікації
errors.title_too_long = Ваш заголовок задовгий
errors.remote_failed = Віддалений запит не виконано
errors.service_unavailable = Служба надсилання тимчасово недоступна. Спробуйте ще раз пізніше.
errors.forum_not_found = Форум не знайдено
errors.forum_not_found_in_directory = Форум не знайдено в каталозі
errors.not_allowed_to_post = Публікувати не дозволено
errors.access_denied = Доступ заборонено
errors.remote = Віддалений сервер не зміг виконати запит
errors.unable_to_connect_to_server = Не вдалося під'єднатися до сервера
errors.invalid_post_id = Невірний ID допису
errors.invalid_title = Недійсна назва
errors.invalid_body = Недійсне тіло
errors.invalid_id = Недійсний ID

attachment.errors.denied = Доступ заборонено
attachment.errors.not_found = Вкладення не знайдено
attachment.errors.unavailable = Вкладення тимчасово недоступне
