[labels]
app.name = Air
errors.identity_changed = آپ کا اکاؤنٹ تبدیل ہو گیا۔ محفوظ کرنے سے پہلے دوبارہ لوڈ کریں۔
errors.invalid_request = غلط درخواست
errors.missing_field = مطلوبہ خانہ غائب ہے
errors.not_found = نہیں ملا
errors.not_logged_in = جاری رکھنے کے لیے سائن ان کریں
errors.body_is_required = براہ کرم جمع کرنے سے پہلے کچھ لکھیں
errors.body_too_long = آپ کا پیغام بہت طویل ہے
errors.title_is_required = براہ کرم اپنی پوسٹ کو ایک عنوان دیں
errors.title_too_long = آپ کا عنوان بہت طویل ہے
errors.remote_failed = ریموٹ درخواست ناکام ہوگئی
errors.service_unavailable = جمع کرانے کی سروس عارضی طور پر دستیاب نہیں ہے۔ براہ کرم بعد میں دوبارہ کوشش کریں۔
errors.forum_not_found = فورم نہیں ملا
errors.forum_not_found_in_directory = ڈائریکٹری میں فورم نہیں ملا
errors.not_allowed_to_post = پوسٹ کرنے کی اجازت نہیں
errors.access_denied = رسائی مسترد
errors.remote = ریموٹ سرور درخواست مکمل نہیں کر سکا
errors.unable_to_connect_to_server = سرور سے کنیکٹ ہونے سے قاصر
errors.invalid_post_id = غلط پوسٹ ID
errors.invalid_title = غلط عنوان
errors.invalid_body = غلط باڈی
errors.invalid_id = غلط ID

attachment.errors.denied = رسائی مسترد
attachment.errors.not_found = اٹیچمنٹ نہیں ملی
attachment.errors.unavailable = منسلکہ عارضی طور پر دستیاب نہیں
