[labels]
app.name = Air
errors.identity_changed = آپ کا اکاؤنٹ تبدیل ہو گیا۔ محفوظ کرنے سے پہلے دوبارہ لوڈ کریں۔
errors.invalid_request = غلط درخواست
errors.missing_field = مطلوبہ خانہ غائب ہے
errors.not_found = نہیں ملا
errors.not_logged_in = جاری رکھنے کے لیے سائن ان کریں
