[labels]
app.name = Air
errors.identity_changed = Hisobingiz o'zgardi. Saqlashdan oldin qayta yuklang.
errors.invalid_request = Notoʻgʻri soʻrov
errors.missing_field = Majburiy maydon yo'q
errors.not_found = Topilmadi
errors.not_logged_in = Davom etish uchun kiring
errors.body_is_required = Yuborishdan oldin biror narsa yozing
errors.body_too_long = Xabaringiz juda uzun
errors.title_is_required = Postingizga sarlavha bering
errors.title_too_long = Sarlavhangiz juda uzun
errors.remote_failed = Masofaviy soʻrov bajarilmadi
errors.service_unavailable = Yuborish xizmati vaqtincha mavjud emas. Iltimos, keyinroq qayta urinib koʻring.
errors.forum_not_found = Forum topilmadi
errors.forum_not_found_in_directory = Forum katalogda topilmadi
errors.not_allowed_to_post = Post qoldirishga ruxsat yo‘q
errors.access_denied = Kirish rad etildi
errors.remote = Masofadagi server so'rovni yakunlay olmadi
errors.unable_to_connect_to_server = Serverga ulanib bo‘lmadi
errors.invalid_post_id = Noto‘g‘ri post ID
errors.invalid_title = Noto‘g‘ri sarlavha
errors.invalid_body = Noto‘g‘ri matn
errors.invalid_id = Noto‘g‘ri ID

attachment.errors.denied = Kirish rad etildi
attachment.errors.not_found = Biriktirma topilmadi
attachment.errors.unavailable = Biriktirma vaqtincha mavjud emas
