[labels]
app.name = Air
errors.identity_changed = I-akhawunti yakho itshintshile. Layisha kwakhona ngaphambi kokugcina.
errors.invalid_request = Isicelo esingasebenziyo
errors.missing_field = Kulahleke intsimi efunekayo
errors.not_found = Ayifunyanwanga
errors.not_logged_in = Ngena ukuze uqhube

attachment.errors.denied = Akuvumelekanga ukungena
attachment.errors.not_found = Incwadi eqhotyoshelweyo ayifumaneki
attachment.errors.unavailable = Isincamathiselo asifumaneki okwethutyana
