[labels]
app.name = Air
errors.identity_changed = I-akhawunti yakho itshintshile. Layisha kwakhona ngaphambi kokugcina.
errors.invalid_request = Isicelo esingasebenziyo
errors.missing_field = Kulahleke intsimi efunekayo
errors.not_found = Ayifumanekanga
errors.not_logged_in = Ngena ukuze uqhube
errors.body_is_required = Nceda ubhale okuthile phambi kokungenisa
errors.body_too_long = Umyalezo wakho mude kakhulu
errors.title_is_required = Nceda nika iposti yakho isihloko
errors.title_too_long = Isihloko sakho side kakhulu
errors.remote_failed = Isicelo sokukude asiphumelelanga
errors.service_unavailable = Inkonzo yokungenisa ayifumaneki okwethutyana. Nceda uzame kwakhona kamva.
errors.forum_not_found = Iforamu ayifumaneki
errors.forum_not_found_in_directory = Iforamu ayifumaneki kwidirektri
errors.not_allowed_to_post = Akuvunyelwanga ukuposta
errors.access_denied = Ufikelelo lwaliwe
errors.remote = Iseva ekude ayikwazanga ukugqiba isicelo
errors.unable_to_connect_to_server = Akukwazeki ukunxulumana neseva
errors.invalid_post_id = I-ID yeposti engasebenziyo
errors.invalid_title = Isihloko esingasebenziyo
errors.invalid_body = Umzimba ongasebenziyo
errors.invalid_id = I-ID engasebenziyo

attachment.errors.denied = Ufikelelo lwaliwe
attachment.errors.not_found = Incwadi eqhotyoshelweyo ayifumaneki
attachment.errors.unavailable = Isincamathiselo asifumaneki okwethutyana
