[labels]
app.name = Air
errors.identity_changed = דײַן קאָנטע האָט זיך געביטן. לאָד איבער איידער דו שפּאָרסט.
errors.invalid_request = אומגילטיקע בקשה
errors.missing_field = נייטיקער פֿעלד פֿעלט
errors.not_found = נישט געפֿונען
errors.not_logged_in = לאָג אַרײַן צו פֿאָרזעצן
errors.body_is_required = ביטע שרײַבט עפּעס פֿאַרן אַרײַנשיקן
errors.body_too_long = אייער מעלדונג איז צו לאַנג
errors.title_is_required = ביטע גיט אײַער פּאָסטונג אַ קעפּל
errors.title_too_long = אייער טיטל איז צו לאַנג
errors.remote_failed = ווייטע אנפרעג איז דורכגעפאלן
errors.service_unavailable = דער אַרײַנגעב־דינסט איז צײַטווײַליק נישט צוטריטלעך. ביטע פּרּווט נאָך אַ מאָל שפּעטער.
errors.forum_not_found = פֿאָרום נישט געפֿונען
errors.forum_not_found_in_directory = פֿאָרום נישט געפֿונען אין דירעקטאָריע
errors.not_allowed_to_post = נישט דערלויבט צו פּאָסטן
errors.access_denied = צוטריט אָפּגעזאָגט
errors.remote = דער ווײַטער סערווער האָט נישט געקענט פֿאַרענדיקן די בקשה
errors.unable_to_connect_to_server = נישט מעגלעך צו פֿאַרבינדן צו סערווער
errors.invalid_post_id = אומגילטיקער פּאָסט ID
errors.invalid_title = אומגילטיקער קעפּל
errors.invalid_body = אומגילטיקער גוף
errors.invalid_id = אומגילטיקער ID

attachment.errors.denied = צוטריט אָפּגעזאָגט
attachment.errors.not_found = צוגעלייגטס נישט געפֿונען
attachment.errors.unavailable = צוגאב איז דערווייל נישט פאראן
