[labels]
app.name = Air
errors.identity_changed = Àkàǹtì rẹ ti yípadà. Tún gbé e wọlé kí o tó fi pamọ́.
errors.invalid_request = Ìbéèrè kò tọ́
errors.missing_field = Pápá tí a nílò kò sí
errors.not_found = A kò rí i
errors.not_logged_in = Wọlé láti tẹ̀síwájú
errors.body_is_required = Jọ̀wọ́ kọ ohun kan kí o tó fi ránṣẹ́
errors.body_too_long = Ifiranṣẹ rẹ gun ju
errors.title_is_required = Jọ̀wọ́ fún ìfìwéránṣẹ́ rẹ ní àkòrí
errors.title_too_long = Akọle rẹ gun ju
errors.remote_failed = Ìbéèrè jíjìn kùnà
errors.service_unavailable = Iṣẹ́ ìfisílẹ̀ kò sí fún ìgbà díẹ̀. Jọ̀wọ́ gbìyànjú lẹ́ẹ̀kansí nígbà tó bá yá.
errors.forum_not_found = Forum kò sí
errors.forum_not_found_in_directory = Forum kò sí ní directory
errors.not_allowed_to_post = A kò gbà láti firanṣẹ́
errors.access_denied = A kọ̀ ìwọlé
errors.remote = Sáfà tó jìnnà kò lè parí ìbéèrè náà
errors.unable_to_connect_to_server = Kò lè sopọ̀ mọ́ server
errors.invalid_post_id = ID ìfìránṣẹ́ kò tọ́
errors.invalid_title = Àkọlé kò tọ́
errors.invalid_body = Ara kò tọ́
errors.invalid_id = ID kò tọ́

attachment.errors.denied = A kọ̀ ìwọlé
attachment.errors.not_found = Ìṣọ̀kan kò sí
attachment.errors.unavailable = Àmúso kò sí fún ìgbà díẹ̀
