[labels]
app.name = Air
errors.identity_changed = I-akhawunti yakho ishintshile. Layisha kabusha ngaphambi kokulondoloza.
errors.invalid_request = Isicelo esingavumelekile
errors.missing_field = Kulahleke inkambu edingekayo
errors.not_found = Ayitholakalanga
errors.not_logged_in = Ngena ngemvume ukuze uqhubeke

attachment.errors.denied = Ukufinyelela kuvinjelwe
attachment.errors.not_found = Okunamathiselwe akutholakali
attachment.errors.unavailable = Isinamathiselo asitholakali okwesikhashana
