[labels]
app.name = Air
errors.identity_changed = I-akhawunti yakho ishintshile. Layisha kabusha ngaphambi kokulondoloza.
errors.invalid_request = Isicelo esingavumelekile
errors.missing_field = Kulahleke inkambu edingekayo
errors.not_found = Ayitholakalanga
errors.not_logged_in = Ngena ngemvume ukuze uqhubeke
errors.body_is_required = Sicela ubhale okuthile ngaphambi kokuthumela
errors.body_too_long = Umyalezo wakho mude kakhulu
errors.title_is_required = Sicela unike umbhalo wakho isihloko
errors.title_too_long = Isihloko sakho side kakhulu
errors.remote_failed = Isicelo sesilawuli kude sihlulekile
errors.service_unavailable = Insiza yokuthumela ayitholakali okwesikhashana. Sicela uzame futhi kamuva.
errors.forum_not_found = Iforamu ayitholakali
errors.forum_not_found_in_directory = Iforamu ayitholakali kuhlukezi
errors.not_allowed_to_post = Akuvunyelwe ukuthumela
errors.access_denied = Ukufinyelela kuvinjelwe
errors.remote = Iseva ekude ayikwazanga ukuqedela isicelo
errors.unable_to_connect_to_server = Akukwazeki ukuxhumeka kuseva
errors.invalid_post_id = I-ID yokuthunyelwe engavumelekile
errors.invalid_title = Isihloko esingavumelekile
errors.invalid_body = Umzimba ongavumelekile
errors.invalid_id = I-ID engavumelekile

attachment.errors.denied = Ukufinyelela kuvinjelwe
attachment.errors.not_found = Okunamathiselwe akutholakali
attachment.errors.unavailable = Isinamathiselo asitholakali okwesikhashana
