// Copyright © 2026 Mochisoft OÜ
// SPDX-License-Identifier: AGPL-3.0-only
// This file is part of Mochi, licensed under the GNU AGPL v3 with the
// Mochi Application Interface Exception - see license.txt and license-exception.md.
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { MESSAGES, SPOKEN, voice_queue, voice_step, type Message } from './voice'

// The voice alert system (NATOPS A1-F18AC-NFM-000 2.17.3, GPWS 2.17.5). The
// queue is imported; the caution tone's hand-over to the voice and the GPWS
// gear-up landing condition live in engine.ts, which cannot be imported (WebGL
// at module scope), so they are read as text and run against stand-ins, as
// hud-status.test.ts does.
const source = readFileSync(fileURLToPath(new URL('./engine.ts', import.meta.url)), 'utf8')
const tool = readFileSync(fileURLToPath(new URL('../../../tools/voice.py', import.meta.url)), 'utf8')
const tail = /\n\tcaution_list=rows;\n[\s\S]*?\n\tvoice_step\(voice,sim_time,active,audio_voice\); \}\n/.exec(source)?.[0] ?? ''
const ground = /\n\t\t\t\{ const slow=\(ownship\.cas\?\?ownship\.speed\)<102\.9;[\s\S]*?gpws\.waveoff\)>60; \}\n/.exec(source)?.[0] ?? ''

const LENGTH: Record<Message, number> = { 'ENGINE FIRE LEFT': 2.8, 'ENGINE FIRE RIGHT': 2.7, 'CHECK GEAR': 1.7, 'FLIGHT CONTROLS': 2.6, 'ENGINE LEFT': 2.1, 'ENGINE RIGHT': 2, 'FUEL LOW': 1.6, BINGO: 1.1 }

// Runs the queue at 10 Hz from 0 to end seconds, with the messages each time
// has on, and returns what started when.
function listen(end: number, on: (time: number) => Message[]): [number, Message][] {
  const queue = voice_queue(), heard: [number, Message][] = []
  for (let tick = 0; tick <= end * 10; tick++) {
    const time = tick / 10
    voice_step(queue, time, new Set(on(time)), (message) => { heard.push([time, message]); return LENGTH[message] })
  }
  return heard
}
const between = (time: number, from: number, to: number) => time >= from && time < to

describe('the voice alert queue', () => {
  it('announces a message once when its condition comes on, with no reset', () => {
    expect(listen(100, () => ['FUEL LOW'])).toEqual([[0, 'FUEL LOW']])
    expect(listen(100, (t) => (t >= 12 ? ['ENGINE LEFT'] : []))).toEqual([[12, 'ENGINE LEFT']])
  })

  it('announces again only after the condition has been gone for 5 seconds and returns', () => {
    const flicker = listen(60, (t) => (between(t, 10.1, 14.9) ? [] : ['ENGINE RIGHT'])) // gone 4.8 s
    expect(flicker).toEqual([[0, 'ENGINE RIGHT']])
    const recurs = listen(60, (t) => (between(t, 10.1, 15.5) ? [] : ['ENGINE RIGHT'])) // gone 5.4 s
    expect(recurs).toEqual([[0, 'ENGINE RIGHT'], [15.5, 'ENGINE RIGHT']])
  })

  it('never interrupts a message: a higher priority one waits for it and a short gap', () => {
    const heard = listen(20, (t) => (t >= 1 ? ['FUEL LOW', 'ENGINE FIRE LEFT'] : ['FUEL LOW']))
    expect(heard[0]).toEqual([0, 'FUEL LOW'])
    expect(heard[1][1]).toBe('ENGINE FIRE LEFT')
    expect(heard[1][0]).toBeGreaterThanOrEqual(1.6)
    expect(heard[1][0]).toBeLessThan(2.1)
  })

  it('takes the waiting messages in priority order, the fires left before right', () => {
    const heard = listen(29, (t) => (t < 0.5 ? ['BINGO'] : ['BINGO', 'FUEL LOW', 'ENGINE RIGHT', 'ENGINE FIRE RIGHT', 'ENGINE FIRE LEFT']))
    expect(heard.map(([, message]) => message)).toEqual(['BINGO', 'ENGINE FIRE LEFT', 'ENGINE FIRE RIGHT', 'ENGINE RIGHT', 'FUEL LOW'])
  })

  it('drops a waiting message whose condition clears before its turn, and says it if it returns', () => {
    const heard = listen(40, (t) => ['ENGINE FIRE LEFT', ...(between(t, 1, 2) || t >= 20 ? ['FLIGHT CONTROLS' as Message] : [])])
    expect(heard).toEqual([[0, 'ENGINE FIRE LEFT'], [20, 'FLIGHT CONTROLS']])
  })

  it('repeats BINGO every 30 seconds and CHECK GEAR every 8 while their conditions hold', () => {
    expect(listen(100, () => ['BINGO']).map(([time]) => time)).toEqual([0, 30, 60, 90])
    expect(listen(30, () => ['CHECK GEAR']).map(([time]) => time)).toEqual([0, 8, 16, 24])
    expect(listen(100, (t) => (t < 40 ? ['BINGO'] : [])).map(([time]) => time)).toEqual([0, 30]) // refuelled
  })
})

describe('the messages', () => {
  it('are raised by cautions and warnings the engine shows', () => {
    for (const key of Object.keys(SPOKEN)) expect(source, key).toMatch(new RegExp(`push\\("${key}"[,)]`))
    expect(SPOKEN.FLAMEOUT).toEqual(['ENGINE LEFT', 'ENGINE RIGHT'])
    expect(SPOKEN['FUEL LO']).toEqual(['FUEL LOW', 'BINGO']) // the fuel is below bingo too
  })

  it('each have a recording, generated by tools/voice.py speaking the message twice', () => {
    for (const message of MESSAGES) {
      const name = message.toLowerCase().replace(/ /g, '-')
      const entry = new RegExp(`"${name}": \\(\\("([^"]+)", "([^"]+)"\\), [\\d.]+, [\\d.]+\\)`).exec(tool)
      expect(entry, message).not.toBeNull()
      const said = (text: string) => text.replace(/[.,!]/g, '').toUpperCase()
      expect([said(entry![1]), said(entry![2])], message).toEqual([message, message])
      expect(existsSync(fileURLToPath(new URL(`../assets/voice/${name}.mp3`, import.meta.url))), `${name}.mp3`).toBe(true)
    }
  })
})

type Row = [string, string, boolean]
interface Moment { rows: Row[]; ready: boolean; gear?: boolean }
interface Result { tones: string[]; lamp: boolean; active: string[] }
// Runs cautions_update's tail once per moment, and returns each moment's tones,
// the MASTER CAUTION lamp and the messages handed to the queue.
function cautions(moments: Moment[]): Result[] {
  if (!tail) throw new Error('cautions_update tail not found in engine.ts')
  const run = new Function('SPOKEN', 'moments', `let caution_keys=new Set(), caution_lamp=false, bingo_nag=0, caution_list=[], sim_time=0, ready=false, tones=[], active_passed=[];
    const voice={}, gpws={gear:false};
    const audio_caution=()=>tones.push("caution"), audio_warning=()=>tones.push("warning"), audio_voiced=()=>ready, audio_voice=()=>0;
    const voice_step=(queue,time,set)=>{ active_passed=[...set]; };
    function cautions_update(rows){ ${tail}
    return moments.map((m)=>{ ready=m.ready; gpws.gear=!!m.gear; tones=[]; sim_time+=1/60; cautions_update(m.rows); return { tones, lamp:caution_lamp, active:active_passed }; });`)
  return run(SPOKEN, moments) as Result[]
}
const row = (key: string, red = false): Row => [key, key, red]

describe('the voice takes over from the caution tone', () => {
  it('announces a voiced caution in place of the master caution tone, and still lights the lamp', () => {
    const [voiced] = cautions([{ rows: [row('FUEL LO')], ready: true }])
    expect(voiced.tones).toEqual([])
    expect(voiced.lamp).toBe(true)
    expect(voiced.active.sort()).toEqual(['BINGO', 'FUEL LOW'])
  })

  it('gives a FIRE warning its voice alone', () => {
    const [fire] = cautions([{ rows: [row('L ENG FIRE', true)], ready: true }])
    expect(fire.tones).toEqual([])
    expect(fire.active).toEqual(['ENGINE FIRE LEFT'])
  })

  it('tones a caution with no voice, alongside a voiced one', () => {
    const [both] = cautions([{ rows: [row('R ENG'), row('FUEL LEAK')], ready: true }])
    expect(both.tones).toEqual(['caution'])
    expect(both.active).toEqual(['ENGINE RIGHT'])
  })

  it('falls back to the tone while the recording is not ready', () => {
    const [caution] = cautions([{ rows: [row('FCS')], ready: false }])
    expect(caution.tones).toEqual(['caution'])
    expect(caution.active).toEqual([])
    const [warning] = cautions([{ rows: [row('R ENG FIRE', true)], ready: false }])
    expect(warning.tones).toEqual(['warning'])
  })

  it('repeats BINGO as a tone only when the voice cannot', () => {
    const minute = (ready: boolean) => cautions(Array.from({ length: 3700 }, () => ({ rows: [row('BINGO')], ready })))
    expect(minute(false).flatMap((m) => m.tones)).toEqual(['caution', 'caution', 'caution']) // the new caution, then 30 s and 60 s
    expect(minute(true).flatMap((m) => m.tones)).toEqual([])
  })

  it('hands CHECK GEAR to the queue while the GPWS condition holds', () => {
    const [due, clear] = cautions([{ rows: [], ready: true, gear: true }, { rows: [], ready: true, gear: false }])
    expect(due.active).toEqual(['CHECK GEAR'])
    expect(clear.active).toEqual([])
  })
})

interface Sample { agl: number; sink: number; cas: number; gear?: number; grounded?: boolean; flying?: boolean }
// Flies the GPWS block at 10 Hz from 0 to end seconds and returns CHECK GEAR's
// state at each whole second.
function gpws(end: number, at: (time: number) => Sample): boolean[] {
  if (!ground) throw new Error('GPWS block not found in engine.ts')
  const run = new Function('end', 'at', `const gpws={wheels:-Infinity,waveoff:-Infinity,climb:-1,gear:false}, out=[];
    for(let tick=0;tick<=end*10;tick++){ const sim_time=tick/10, s=at(sim_time), agl=s.agl, sink=s.sink, flying=s.flying??!s.grounded;
      const ownship={cas:s.cas, speed:s.cas, gear:s.gear??1, grounded:!!s.grounded};
      ${ground}
      if(tick%10===0) out.push(gpws.gear); }
    return out;`)
  return run(end, at) as boolean[]
}
const KNOTS = 0.5144
const approach = (sample: Partial<Sample> = {}): Sample => ({ agl: 120, sink: 3, cas: 140 * KNOTS, gear: 1, ...sample })
const cruise: Sample = { agl: 1500, sink: 0, cas: 300 * KNOTS }

describe('the GPWS CHECK GEAR condition', () => {
  const launched = (time: number) => time < 5 // on the wheels for the first five seconds

  it('holds descending below 150 ft under 200 knots with the gear up, over a minute after the wheels', () => {
    const state = gpws(100, (t) => (launched(t) ? { ...cruise, agl: 0, cas: 0, grounded: true } : t < 90 ? cruise : approach()))
    expect(state[95]).toBe(true)
    expect(state[89]).toBe(false)
  })

  it('stays quiet within a minute of the wheels', () => {
    const state = gpws(60, (t) => (launched(t) ? { ...cruise, agl: 0, cas: 0, grounded: true } : t < 50 ? cruise : approach()))
    expect(state[55]).toBe(false)
  })

  it('needs the gear not down and locked, under 200 knots, descending, below 150 ft, and flying', () => {
    const after = (sample: Sample) => gpws(100, (t) => (t < 90 ? cruise : sample))[95]
    expect(after(approach())).toBe(true)
    expect(after(approach({ gear: 0.5 }))).toBe(true) // still travelling
    expect(after(approach({ gear: 0.01 }))).toBe(false) // down and locked
    expect(after(approach({ cas: 210 * KNOTS }))).toBe(false)
    expect(after(approach({ sink: 0 }))).toBe(false)
    expect(after(approach({ agl: 160 }))).toBe(false)
    expect(after(approach({ flying: false }))).toBe(false)
  })

  it('counts a minute from a waveoff: a 1,000 fpm climb held 5 s below 500 ft and 200 knots', () => {
    const waveoff = (climb: Partial<Sample>, seconds: number) => (t: number) =>
      t < 100 ? cruise : t < 100 + seconds ? { ...approach(), sink: -6, agl: 300, ...climb } : t < 130 ? cruise : approach()
    expect(gpws(170, waveoff({}, 6))[135]).toBe(false) // under a minute since the waveoff
    expect(gpws(170, waveoff({}, 6))[168]).toBe(true) // over a minute
    expect(gpws(170, waveoff({}, 4))[135]).toBe(true) // too short to be a waveoff
    expect(gpws(170, waveoff({ agl: 600 }, 6))[135]).toBe(true) // above 500 ft
    expect(gpws(170, waveoff({ sink: -4 }, 6))[135]).toBe(true) // under 1,000 fpm
    const twice = (t: number) => (between(t, 100, 104) || between(t, 110, 114) ? { ...approach(), sink: -6, agl: 300 } : t < 130 ? cruise : approach())
    expect(gpws(170, twice)[135]).toBe(true) // two short climbs are not one long one
  })
})
