#!/usr/bin/env python3
# Copyright © 2026 Mochisoft OÜ
# SPDX-License-Identifier: AGPL-3.0-only
# This file is part of Mochi, licensed under the GNU AGPL v3 with the
# Mochi Application Interface Exception - see license.txt and license-exception.md.
"""Pack the brighter stars of the Yale Bright Star Catalogue into web/src/game/stars.ts.

Source: Hoffleit & Warren, The Bright Star Catalogue, 5th Revised Ed. (Yale
University Observatory, 1991), CDS catalogue V/50:
  https://cdsarc.cds.unistra.fr/ftp/V/50/catalog.gz  (format: .../V/50/ReadMe)

Usage: stars.py <catalog> [--limit 4.5]
Each star packs into 6 bytes: right ascension as uint16 (full circle), declination
as int16 (+-90 deg), visual magnitude as uint8 ((V + 2) * 20), B-V colour index as
int8 (* 50). J2000 positions: precession to the present moves them by under 0.4 deg.
"""
import base64
import struct
import sys
from pathlib import Path

catalog = Path(sys.argv[1])
limit = float(sys.argv[sys.argv.index("--limit") + 1]) if "--limit" in sys.argv else 4.5   # a moonlit sky: fainter stars are washed out, and 4.5 keeps ~450 above the horizon
out = Path(__file__).resolve().parent.parent / "web/src/game/stars.ts"

records, brightest = [], None
for line in catalog.read_text(encoding="latin1").splitlines():
    line = line.ljust(197)
    ra_h, ra_m, ra_s = line[75:77].strip(), line[77:79].strip(), line[79:83].strip()
    de_sign, de_d, de_m, de_s = line[83], line[84:86].strip(), line[86:88].strip(), line[88:90].strip()
    vmag, bv = line[102:107].strip(), line[109:114].strip()
    if not (ra_h and de_d and vmag):   # novae and a few non-stellar entries carry no J2000 position
        continue
    magnitude = float(vmag)
    if magnitude > limit:
        continue
    ra = (int(ra_h) + int(ra_m) / 60 + float(ra_s) / 3600) * 15.0
    dec = (int(de_d) + int(de_m) / 60 + int(de_s) / 3600) * (-1 if de_sign == "-" else 1)
    colour = float(bv) if bv else 0.6   # a missing index reads as a sun-like white
    records.append(struct.pack("<HhBb", round(ra / 360.0 * 65536) % 65536, round(dec / 90.0 * 32767),
                               max(0, min(255, round((magnitude + 2.0) * 20))), max(-127, min(127, round(colour * 50)))))
    if brightest is None or magnitude < brightest[0]:
        brightest = (magnitude, line[4:14].strip())

data = base64.b64encode(b"".join(records)).decode()
body = "\n".join(f"  '{data[i:i + 100]}' +" for i in range(0, len(data), 100)).rstrip(" +")
out.write_text(f"""// Copyright © 2026 Mochisoft OÜ
// SPDX-License-Identifier: AGPL-3.0-only
// This file is part of Mochi, licensed under the GNU AGPL v3 with the
// Mochi Application Interface Exception - see license.txt and license-exception.md.

// GENERATED by tools/stars.py - do not edit. The {len(records)} stars of the Yale Bright
// Star Catalogue, 5th Revised Ed. (Hoffleit & Warren 1991, CDS V/50) to visual
// magnitude {limit:.1f}, packed 6 bytes each: RA uint16, Dec int16, (V+2)*20 uint8,
// (B-V)*50 int8, little-endian. J2000 positions.
export const STAR_COUNT = {len(records)}
export const STAR_DATA =
{body}
""")
print(f"{len(records)} stars to V {limit:.1f} (brightest {brightest[1]} at {brightest[0]}), {len(data) // 1024} KB base64 -> {out}")
